### ISSUE TITLE
Documentation requests

### ISSUE THREAD

**Issue by hassount** [AOMediaCodec/SVT-AV1#1008]
The following items need to be documented further:

**Encoder Documentation**
- [x] Fix appendices links in the encoder design document 
- [ ] Block scanning order in the Open and Closed loops
- [ ] Detailed process-by-process description on what changes within pcs and scs
- [ ] Document or remove Open Intra Search
- [ ] Add pictures / explanation of different gop structures
- [ ] Add best way to allocation memory and be consistent
- [ ] Neighbor array graphs need to be explained further
- [ ] Document high level BRC
- [ ] MD Staging / PD Staging documentation 
- [ ] Document the number of threads associated with each process.
- [ ] Add a table to explain segment size limits ( me / encdec / restoration)
- [ ] Add a mapping for the block sizes within SB 
- count_total_num_of_active_blks, depth_scan_all_blks, md_scan_all_blks
- [ ] Revisit the DLF section in the documentation

**Decoder Documentation**
- [ ] Update decoder user guide for known limitations
- [ ] Create a decoder design document

**Comment by PDX-Runner** [comment]
please add documentation similar as https://aomedia.googlesource.com/aom/+/master/README.md to explain the contribution process.
