### ISSUE TITLE
Ffmpeg plugin corrections

### ISSUE THREAD

**Issue by intelmark** [AOMediaCodec/SVT-AV1#1061]
1) Both AV1 ffmpeg patch files need some updating:

  { "rc", "Bit rate control mode", OFFSET(rc_mode),
+      AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 3, VE , "rc"},
+        { "cqp", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 0 },  INT_MIN, INT_MAX, VE, "rc" },
+        { "vbr", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 2 },  INT_MIN, INT_MAX, VE, "rc" },
+        { "cvbr", NULL, 0, AV_OPT_TYPE_CONST,{ .i64 = 3 },  INT_MIN, 
+ INT_MAX, VE, "rc" },

Values for vbr and cvbr seem to be off - I think this should be:

  { "rc", "Bit rate control mode", OFFSET(rc_mode),
+      AV_OPT_TYPE_INT, { .i64 = 0 }, 0, 3, VE , "rc"},
+        { "cqp", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 0 },  INT_MIN, INT_MAX, VE, "rc" },
+        { "vbr", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 1 },  INT_MIN, INT_MAX, VE, "rc" },
+        { "cvbr", NULL, 0, AV_OPT_TYPE_CONST,{ .i64 = 2 },  INT_MIN, 
+ INT_MAX, VE, "rc" },

2) Readme instructions for "With SVT-AV1 alone" need a "make -j $(nproc)" instruction added (as shown for "With SVT-HEVC and SVT-AV1"):

https://github.com/OpenVisualCloud/SVT-AV1/blob/master/ffmpeg_plugin/README.md

With SVT-AV1 alone:

git apply SVT-AV1/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1.patch
./configure --enable-libsvtav1

With SVT-HEVC and SVT-AV1:
git apply SVT-HEVC/ffmpeg_plugin/0001-lavc-svt_hevc-add-libsvt-hevc-encoder-wrapper.patch
git apply SVT-AV1/ffmpeg_plugin/0001-Add-ability-for-ffmpeg-to-run-svt-av1-with-svt-hevc.patch
./configure --enable-libsvthevc --enable-libsvtav1 make -j $(nproc)

**Comment by xuguangxin** [comment]
I think this fixed by https://github.com/AOMediaCodec/SVT-AV1/pull/1352/commits/5deb3a3110d4221e48add7b694e90713297b908a. @intelmark  could you help double confirm it?

thanks

**Comment by intelmark** [comment]
@xuguangxin - I reviewed the changes and the values are correct now.

**Comment by hassount** [comment]
thank you guys
