### ISSUE TITLE
Only Intra Coding

### ISSUE THREAD

**Issue by rubenmt94** [AOMediaCodec/SVT-AV1#1114]
Hi, I have a question about coding with only intra frames, in other words, that the coding is only intra. I am using a series of commands, but I am not sure if they are the correct ones. The commands are:

_SvtAV1EncApp.exe -i RaceHorses.yuv -w 2560 -h 1600 -fps 30 **-intra-period -1** -use-q-file 1 -qp-file qp37.txt -enc-mode 5 -stat-report 1 -stat-file stat/RaceHorses_37.txt -b RaceHorses_37.y4m 2>RaceHorses_37.txt_

Is this script correct to achieve only intra coding? If not, what commands should be used to be intra only intra coding?

Thanks in advance.

**Comment by hassount** [comment]
@rubenmt94 
sorry for the late reply on this, it should be -intra-period 0. please let me know if that does not work

**Comment by praneet195** [comment]
Hi,

When I run this in the current build, I get the following error,
LAD=0 is not supported.

**Comment by rubenmt94** [comment]
Hello, sorry for the delay in my response, but due to the COVID crisis I have not yet been able to test your suggestion. When the health crisis ends I will prove it.
