### ISSUE TITLE
Why pred-struct 0 and 1 are not allowed now?

### ISSUE THREAD

**Issue by spartazhc** [AOMediaCodec/SVT-AV1#1137]
Notice that pred-struct [0,1] are disabled for a long time. (It seems #207 is v0.8.2 milestone)
```c
static EbErrorType verify_settings(
    SequenceControlSet       *scs_ptr)
{
...
    if (config->pred_structure != 2) {
        SVT_LOG("Error instance %u: Pred Structure must be [2]\n", channel_number + 1);
        return_error = EB_ErrorBadParameter;
    }
...
}
```
In #968 and #973 mentioned  manual prediction structure configure, and encoder's features are not ready for hierarchical_levels 0/1/2.

So my questions are:

1.  Why pred-struct 0 and 1 are not allowed now?
2.  Can pred-struct-file option replace the pred-struct?
3.  What else can I do to achieve lower latency?

**Comment by hassount** [comment]
@spartazhc 
this is a WIP and is tracked as part of #1047 once the PRs are in, you would be able to reduce the latency by reducing the prediction structures needed.
