### ISSUE TITLE
Remove width and height Limits (for AVIF)

### ISSUE THREAD

**Issue by mshobohm** [AOMediaCodec/SVT-AV1#12]
Using AV1 Encoders for AVIF Images is a low hanging fruit. Resolutions are often higher than video format 4k (3840x2160), so a static limit for the resolution makes it unusable for this use case. 
-------------------------------------------------------------------------------
Here is my toolchain for generating AVIF Images:
ffmpeg.exe -loglevel quiet -y -i image.png -pix_fmt yuv420p image.y4m
SvtAV1EncApp.exe -i image.y4m -w <imagewidth> -h <imageheight> -b image.ivf
mp4box.exe -add-image image.ivf:primary -ab avif -ab miaf -new image.avif

**Comment by kylophone** [comment]
@hassount, is there any technical reason to constrain the maximum resolution? Can we lift this?

**Comment by hassount** [comment]
@kylophone 
Ultimately, as we are allocating all memory at init time (at least trying to), we would have to have some constrain as it would define the precision of several variable. We can try increasing the limit to handle higher resolutions. This would then require some further digging to make sure that everything is accounted for and not assumed.
