### ISSUE TITLE
Add --version to executables

### ISSUE THREAD

**Issue by sandersaares** [AOMediaCodec/SVT-AV1#1213]
Right now the version info dump is only printed once encoding/decoding starts (in `init_svt_av1_encoder_handle()`). I would like to be able to inspect this info using just a `--version` argument.

**Comment by tianjunwork** [comment]
Hi @sandersaares , you mean add --version to sample app, similar to https://github.com/OpenVisualCloud/SVT-HEVC/pull/388?

**Comment by sandersaares** [comment]
Yes, exactly

**Comment by tianjunwork** [comment]
Hi @sandersaares , @ePirat may work on consolidating version in the source code. Your request will be worked on after that. Thanks for the feedback.

**Comment by hassount** [comment]
has this been addressed ? @ePirat @tianjunwork

**Comment by tianjunwork** [comment]
Hi @ePirat , did you have a chance to work on simplify the versioning like SVT-HEVC?
