### ISSUE TITLE
v0.8.2 && v0.8.3 performance drop largely compare with v0.8.0

### ISSUE THREAD

**Issue by xudongxu135** [AOMediaCodec/SVT-AV1#1268]
I use the cmd below:
ffmpeg -i seq.mp4 -vcodec libsvt_av1 -vsync 0 -vb 2000k -preset 8 -rc 2 -threads 0 ./test.mp4 
on my platform(up to avx2, 48 cores), if I use v0.8.0, for 1080P@30 sequences, it can reach to 44fps.
But when I use the newest version, i.e v0.8.2 or v0.8.3, it can only reach to 22fps, nearly 50% performance degradation. 
Can anyone tell me why? Thank you very much.

**Comment by tianjunwork** [comment]
Hi @OmranAbdelkafi , do you have any information to share about performance difference between the versions?

**Comment by xudongxu135** [comment]
Are there any tools added to the version of 0.8.2 or 0.8.3? 
In v0.8.3, If I want to get an equal encoding speed, compared with v0.8.0, which tools must be closed? How do I tune the parameters? 
Thank you very much for your kind help.

**Comment by silverbacknet** [comment]
One thing I've noticed in watching the patches come in over the last few months is that there have been many bugfixes that have had a small negative performance impact, typically less than 1% but occasionally 2-3%. Some caused crashes, or had the potential to, others corruption or only reduced encoding quality, although I don't think they come close to a 50% overall degradation added together. But then again, they were tested on slower presets, maybe they have an outsize impact on the fastest one.

I don't recall if any specific tools were added to preset 8.

**Comment by xudongxu135** [comment]
Thank you for your reply @silverbacknet. Since the preset 8 is the default one currently, I think this preset will be used most frequently. Can anyone look into this intricate problem?

**Comment by OmranAbdelkafi** [comment]
We will be investigating such matter and will let you know ASAP

**Comment by xudongxu135** [comment]
Is there any progress on this issue?
looking forward to your reply, thanks!

**Comment by hassount** [comment]
I believe the issue has been found and is being resolved, it will take some time as the focus is still VOD and the speed would still be slightly lower than 0.8.0 even after #1420 but we should get there soon with much better quality.

**Comment by xudongxu135** [comment]
update：0.8.5 on my platform, for preset 8, just can only reach to 14fps, slower than 0.8.2 and 0.8.3. But  the quality is much better.

**Comment by hassount** [comment]
@xudongxu135 

Can you check the latest master revision ?

**Comment by xudongxu135** [comment]
@hassount  Thanks for reply. Using the version of the latest master, for preset 8, on my platform(same environment), it can reach to 28fps, quicker than 0.8,2 and 0.8.3(which are only 22fps), much quicker than 0.8.5(which is only 14fps), but still much slower than 0.8.0(44fps).

**Comment by hassount** [comment]
@xudongxu135 thank you for the update, adding —enable-tpl-la 0 should give you a little extra speed, and future PRs will probably close the gap. We’re trying to keep the quality as good as possible while gaining the speed back slowly without loosing much in quality.
