### ISSUE TITLE
Blocking in keyframes with motion

### ISSUE THREAD

**Issue by quietvoid** [AOMediaCodec/SVT-AV1#1297]
Hello, I've encountered a bug where the keyframe quality is heavily affected.

The SVT-AV1 version I'm using is `SVT-AV1 Encoder Lib v0.8.3-22-ga0524a94-dirty`
The source sample and encoded files are available here: https://mega.nz/folder/ZQF3SQrS#gphO2sbPN5W0jWJaWZJffw

The SVT-AV1 0.8.3 and 0.8.2 tag releases are also affected.
The blocking is identical to `0.8.3-22-ga0524a94-dirty`.

SVT-AV1 0.8.1 has similar blocking but the detail within the blocks is correct while it's smoothed out for the newer versions.

These are the encoder options I'm comparing:

Causes the issue:
>.\SvtAv1EncApp.exe -i source-sample.y4m  --fps-num 24000 --fps-denom 1000 --input-depth 10 --keyint 1 --irefresh-type 2 --rc 0 --qp 25 --tile-rows 3 --tile-columns 3 --preset 8 -b out.ivf

No issue:
>.\SvtAv1EncApp.exe -i source-sample.y4m --fps-num 24000 --fps-denom 1000 --input-depth 10 --keyint 100 --irefresh-type 2 --rc 0 --qp 25 --tile-rows 3 --tile-columns 3 --preset 8 -b out.ivf

The only difference is `--keyint 1` to `--keyint 100`.
When the frame is not a keyframe, the encoded image looks as expected.

The blocking however seems to only happen on sudden high motion (and in the in-motion areas). Maybe the bitstream tells a different story.
The outcome with using `--keyint 1` is consistent for single pass and 2 pass, also `--preset` 8 to 4.

Screenshot of the issue (frame 6 of the samples):
![keyint=1](https://user-images.githubusercontent.com/39477805/81763258-d1917000-949c-11ea-8157-034d4b1eb454.png)

Thank you.

**Comment by tianjunwork** [comment]
Hi @quietvoid , thanks for the detailed description. 
As a quick experiment, adding `--enable-altrefs 0` to your `--keyint 1` command line mitigates the blocking artifacts.
Hi @mafonsoN, the problem here is, for **key** frame, using `--keyint 1 --enable-altrefs 1`, the moving area is divided into more small blocks(compared with altref disabled) which makes the blocking artifacts very obvious. Could you help to comment? Is this expected behavior? Thank you.

**Comment by mafonsoN** [comment]
@tianjunwork I'll have a look.

**Comment by quietvoid** [comment]
Furthermore, using tiles (in this case `--tile-rows 3 --tile-columns 3`) makes the blocking more visible.

**Comment by tianjunwork** [comment]
Hi @quietvoid, I tried disabling tile also yesterday, but there was no difference.

**Comment by quietvoid** [comment]
Hmm, maybe I'm remembering wrong. Sorry.

**Comment by tianjunwork** [comment]
It's totally fine. Could you confirm on your side again?
Using `--keyint 1`:
1. Disabling tile ==> no difference?
2. Disabling altref ==> mitigating blocking artifacts.

**Comment by quietvoid** [comment]
That's mostly correct.
There is however a difference with disabling tiles, the blocking is still the same however the block edges are smoother and less visible in the darker areas of the frame.

Disabling altrefs with `--enable-altrefs 0`, the output encode has no visible block edges for me and the image looks fine.

See here for the tiles vs. no tiles images:

![01a](https://user-images.githubusercontent.com/39477805/81851274-31345d80-9527-11ea-916b-2956a506ba1e.png)
![01b](https://user-images.githubusercontent.com/39477805/81851272-31345d80-9527-11ea-9818-b569adfea800.png)

**Comment by tianjunwork** [comment]
Thanks for confirming with more testing.
Maybe you could circle out the different area in above two pictures? I can barely see any difference:)
I think we both agree that `--enable-altrefs` makes the most difference. Let's focus on tuning that one first.

**Comment by quietvoid** [comment]
Agreed.

I made this, hopefully it's easier to see.
<img width="900" alt="zoomed-comp" src="https://user-images.githubusercontent.com/39477805/81858962-8fb30900-9532-11ea-8ab0-1028ab386fe9.png">

**Comment by hassount** [comment]
Can you test this again with the current master.

**Comment by quietvoid** [comment]
Yes it still happens.

![a](https://user-images.githubusercontent.com/39477805/92178645-faa18c00-ee10-11ea-84ff-fab6c2f0b748.png)

I've added the new output bitstream to the same MEGA folder.
