### ISSUE TITLE
Can we specify the number of b-frames?

### ISSUE THREAD

**Issue by praneet195** [AOMediaCodec/SVT-AV1#1341]
Hi,
So Is there anyway I can encode using both p and b frames. I tried using this command but the prediction structure does not change even though I specified it in the command:

`~/ffmpeg_sources/ffmpeg/ffmpeg -y -r 25 -i V000.seq -an -f rawvideo -pix_fmt yuv420p - | ~/SVT-AV1/Bin/Release/SvtAv1EncApp -i stdin -rc 0 --fps 25 -q 18 --min-qp 18 --max-qp 18 -intra-period 24 --pred-struct 1  -w 640 -h 480 --lp 8 -b V000.ivf`

The output is as follows:

SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 640 / 480
SVT [config]: FrameRate / Gop Size                                              : 25 / 25
**SVT [config]: HierarchicalLevels  / PredStructure               : 4 / 2**
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 18 / 33 / 0

As we can see the pred-structure did not change even though i selected low-delay P mode.
I also wanted to know if there was a way to analyze the bitstream generated like FFPROBE?
Also, is there a way in which we can specify the number of b-frames before every other p-frame as in the -bf option in FFMPEG?

**Comment by hassount** [comment]
I believe you're looking for the --hierarchical-levels switch, try --hierarchical-levels 3, that would cut the amount of B frames per gop by 2

**Comment by silverbacknet** [comment]
I remember that more flexible structure is on the roadmap for later this year, specifically for scenechange, but I can't dig up the actual comment. It would certainly be nice to have x264-style flexible use of frametypes rather than strictly hierarchical.

**Comment by kedartatwawadi** [comment]
I am a bit confused about the `--pred-struct` and `--hierarchical-levels` options you elaborate on how they impact the I,P,B frame distribution?

**Comment by hassount** [comment]
seems that I missed this issue:



> I remember that more flexible structure is on the roadmap for later this year, specifically for scenechange, but I can't dig up the actual comment. It would certainly be nice to have x264-style flexible use of frametypes rather than strictly hierarchical.

More flexible is towards being able to support 0B to 31B, but it will always be hierarchical. if really needed, you can customize your own reference structure by customizing per minigop the reference assignment using the pred structure config files



> I am a bit confused about the `--pred-struct` and `--hierarchical-levels` options you elaborate on how they impact the I,P,B frame distribution?

--pred-struct would specify whether it's random access or low delay pred structures (this is not working yet)
--hierarchical-levels would specify the amount of pictures in the minigop with all pictures in the minigop being B frames including the base layer pictures (they look to the past only but they can have more than 1 reference)

**Comment by kedartatwawadi** [comment]
Thansk @hassount .. I am able to encode using the following pred file. Can you let me know if this looks reasonable? (for no Bframes) 

`#keyword           display_order decode_order temporal_layer num_ref_list0 num_ref_list1 diff_poc_ref_list0 diff_poc_ref_list1
PredStructEntry :  0             0            0              2             2             1 2                1 2
PredStructEntry :  1             1            0              2             2             1 2                1 2
PredStructEntry :  2             2            0              2             2             1 2                1 2
PredStructEntry :  3             3            0              2             2             1 2                1 2
PredStructEntry :  4             4            0              2             2             1 2                1 2
PredStructEntry :  5             5            0              2             2             1 2                1 2
PredStructEntry :  6             6            0              2             2             1 2                1 2
PredStructEntry :  7             7            0              2             2             1 2                1 2

`
