### ISSUE TITLE
SVT_AV1 encoding without any B-frames

### ISSUE THREAD

**Issue by kedartatwawadi** [AOMediaCodec/SVT-AV1#1381]
I wanted to know if it is possible to encode a video without any B-frames (only I and P frames). 
I tried the options ` --hierarchical-levels 3 --pred-struct 0`, but that seems to be producing blocks with LAST_FRAME and BWDREF_FRAME as the reference, implying that there is some referencing with a future frame. 

Also, more clarity on what a BWDREF_FRAME is would be great! 

<img width="1361" alt="Screen Shot 2020-07-15 at 2 29 44 PM" src="https://user-images.githubusercontent.com/1708665/87697150-96cee100-c746-11ea-970d-48ee56e35461.png">

**Comment by kedartatwawadi** [comment]
This might a duplicated/related to the issue [1341](https://github.com/OpenVisualCloud/SVT-AV1/issues/1341)

**Comment by praneet195** [comment]
Hey, 
This is going to be off topic.
If possible can you please provide the details to your AOMAnalyzer build? I'm unable to get it working in it's current state

**Comment by kedartatwawadi** [comment]
Here is the script i used to get AOMAnalyzer working:
https://gist.github.com/kedartatwawadi/4eaddeafccb83497260666ba071e3b3c
