### ISSUE TITLE
API/ABI Versioning

### ISSUE THREAD

**Issue by silverbacknet** [AOMediaCodec/SVT-AV1#1417]
#1408 will change the API, and it got me thinking about versioning. Many open source projects have some sort of ABI_VERSION separate from their actual version, that gets bumped up only when the API/ABI changes. If there's a mismatch, it'll either fall back or just error out. SVT-AVI has SVT_VERSION_* defines for its version number, but they aren't used anywhere yet, and the burden is on the user to check each of them.

I think it would be a good idea to have something more like ffmpeg or aom, with its `AOM_IMAGE_ABI_VERSION` (which is used and incremented separately for dependent ABIs as well, as in `#define AOM_CODEC_ABI_VERSION (5 + AOM_IMAGE_ABI_VERSION)`). Since the API doesn't always change version to version, and you certainly don't want clients to crash once things are more stable, maybe this would be a good idea?

**Comment by hassount** [comment]
@ePirat would you be able to help with this ? I believe the API / ABI is now becoming stable enough for such versioning to be added.

**Comment by ePirat** [comment]
@hassount Sorry, I completely missed this somehow as I got no mail notifications for the mention here…

This shouldn't be hard to do.

**Comment by ePirat** [comment]
Currently the API/ABI version is effectively the project version:

```
libSvtAv1Dec.0.8.4.dylib libSvtAv1Enc.0.8.4.dylib
libSvtAv1Dec.0.dylib     libSvtAv1Enc.0.dylib
```

Do we want to keep it that way or do we want to detach the project version from the API/ABI version?
Given that for some changes I guess the decoder API can be broken while the encoder API is not,
it might make sense to not have them share the same version.
