### ISSUE TITLE
[REPO Moving][Announcement] AOM adopts SVT-AV1

### ISSUE THREAD

**Issue by hassount** [AOMediaCodec/SVT-AV1#1425]
As just [announced by AOMedia](https://www.businesswire.com/news/home/20200820005599/en/AOMedia-Software-Implementation-Working-Group-Bring-AV1), a new Software Implementation Working Group (SIWG) has been formed to create a production-ready AV1 encoder implementation that will enable ever-growing video delivery services and deliver excellent video compression versus computational complexity tradeoffs across a wide variety of video applications. This source code repository will be moving by 9/7 to a new [location](https://github.com/AOMediaCodec/SVT-AV1) in support of this exciting announcement. [As the momentum behind AV1 continues](https://itpeernetwork.intel.com/open-source-svt-av1/#gs.ca8afp), we are excited to see SVT-AV1 being used as the production implementation for next generation video services.

**Comment by gnafuthegreat** [comment]
Has there been any talk of a name change as part of the move?  Nothing wrong with "SVT-AV1", but now would be the time to rename if there were any candidates.  Will this still be considered part of the SVT family, or is it expected to diverge over time?  If the latter, then a name change could be appropriate.  If it's just a chance of home, then keeping the name is of course understandable.

Related to that, will the OpenVisualCloud repo remain as its own variant, or is this a complete move?

**Comment by hassount** [comment]
@gnafuthegreat 
It has been decided that the name remains as is for continuity.
It may or may not diverge, I would expect the underlying architecture to remain similar
The repo will move with all history and issues / PR.

**Comment by gnafuthegreat** [comment]
Thanks for clarifying/confirming.  This is an exciting move!

**Comment by hassount** [comment]
Closing as the move happened
