### ISSUE TITLE
c and avx2 mismatch

### ISSUE THREAD

**Issue by OmranAbdelkafi** [AOMediaCodec/SVT-AV1#1428]
## Description 
Compared obj-1-fast (8bit and 10bit) using c vs default(AVX2) for M0 and M4

## Sample Command line 
 ./SvtAv1EncApp -enc-mode 0 -w 1920 -h 1080 -bit-depth 8 -fps-num 30000 -fps-denom 1001  -n  60 -q 20  -intra-period  119  -asm c -enable-tpl-la 1  -lad 16 -lp 1  -i  aspen_1080p_60f.yuv  -b  aspen_1080p_60f_Q20.bin

## Branch used : 
Head branch from PR #1418

## Results
Bitstreams mismatch between the two different encodings.

**Comment by EricLamVCD** [comment]
Tested thaloundeskmtg 10bit 360p clip for M5: 
  | Speed Deviation  | BD-Rate   Deviation | Memory   Deviation
-- | -- | -- | --
asm-sse4_1 vs asm-c - M5 - 10bit | 0.07% | 0.00% | 0.01%
asm-sse3 vs asm-c  - M5 - 10bit | 0.00% | 0.00% | 0.00%
asm-avx2 vs asm-c  - M5 - 10bit | 0.06% | 0.00% | 0.02%

**Comment by EricLamVCD** [comment]
Tested thaloundeskmtg 10bit 360p clip: 
  | Speed Deviation  | BD-Rate   Deviation | Memory   Deviation
-- | -- | -- | --
asm-sse4_1 vs asm-c - M5 - 10bit | 58.90% | 0.00% | 0.05%
asm-sse3 vs asm-c  - M5 - 10bit | 0.38% | 0.00% | 0.02%
asm-avx2 vs asm-c  - M5 - 10bit | 1577.44% | 0.01% | 0.24%

**Comment by ttrigui** [comment]
@spawlows can you please look into this. It seems that the mismatch is between AVX2 and C. SSE3 and SSE4 are fine.

**Comment by spawlows** [comment]
I looking on this. On this moment I confirm issue, and this is not related with sad_loop

**Comment by spawlows** [comment]
Fixed #1485

**Comment by OmranAbdelkafi** [comment]
closed with PR#1485
