### ISSUE TITLE
Support for 4:4:4

### ISSUE THREAD

**Issue by jonsneyers** [AOMediaCodec/SVT-AV1#1433]
Currently, SVT-AV1 only supports 4:2:0 chroma subsampling. In particular for AVIF, it is desirable to also be able to encode 4:4:4, since on some images (e.g. containing colored text), chroma subsampling artifacts can be too strong to be acceptable.

Is it planned to add 4:4:4 support to SVT-AV1?

**Comment by hassount** [comment]
I don't see that we'll have the bandwidth to implement this this year but it could be scheduled for next year depending on the use cases supported.
