### ISSUE TITLE
Film Grain memory and assert failures

### ISSUE THREAD

**Issue by OmranAbdelkafi** [AOMediaCodec/SVT-AV1#1444]
## Description :
We have fixed the library link for the film grain option in order to close issue #1322. We submitted PR #1426 for that but we have noticed some issues : 
1- film grain unit test failure for the PR #1426  due to memory allocation.
2 - Some assert failure when performing some testings .
3 - Compared film grain performance within libaom vs svt : Almost same Visual Quality effect while for svt there is an increase in the memory usage.

##  Sample error/warning message: 
1 - for the film grain unit test : "SvtMalloc[fatal]: allocate memory failed, at D:\a\SVT-AV1\SVT- 
     AV1\Source\Lib\Encoder\Codec\noise_model.c, L1499"
2- For the assert failure : "Svt[error]: Solving latest noise equation system failed 0!"
3- Memory increase : Up to 20% in some cases

## Related issue : 
#1322

**Comment by tszumski** [comment]
After #1562 was merged only one issue left:
2 - Some assert failure when performing some testings . "Svt[error]: Solving latest noise equation system failed 0!"

**Comment by tszumski** [comment]
Error "Solving latest noise equation system failed" happens only when "-film-grain" param is small, for example: 
**SVT-AV1**
```
-w 176 -h 144 -bit-depth 8 -n 50 -film-grain {val} --preset 8 -i BQSquare_176x144_60.yuv  -b out.bin 
```		
-film-grain >= 3 works fine
-film-grain < 3 (1 or 2) failed with "Solving latest noise equation system failed"


I also checked how AOM behave for similar command line:
**AOM**
```
-w 176 -h 144 -b 8 --limit=50 --denoise-noise-level={val} --cpu-used=6 -o out.bin BQSquare_176x144_60.yuv
```	 
--denoise-noise-level >= 3 works fine
--denoise-noise-level < 2 (1 or 2) failed with "Solving latest noise equation system failed"

**Comment by quietvoid** [comment]
The assert failures seem to be source sample dependent.
I've had none for one using `--film-grain 7` while another did print the failure with `--film-grain 10`.
