### ISSUE TITLE
2-pass crf/vbr mode comparision (libsvt vs libaom) for videocodectracker.dev

### ISSUE THREAD

**Issue by grill05** [AOMediaCodec/SVT-AV1#1450]
Once the 2-pass mode PR gets merged, it might be useful to add this mode to the standard run for videocodectracker.dev

I'm guessing that practically everyone will be using the 2-pass implementation rather than the current one , once the PR goes through, and seeing how it compares with libaom's 2-pass crf/vbr (over time) would be helpful

thanks

**Comment by hassount** [comment]
@grill05  as mentioned in the commit message, this is only a first version of the PR introducing the support and inly passing some initial tests. The work will be ongoing to finish the full implementation. This is a porting of the libaom 2pass engine so there hopefully won’t be too many differences.

**Comment by Felixkruemel** [comment]
How can you actually use crf in ffmpeg with libsvtav1?

-crf doesn't seem to work yet.

Before doing a comparison I would wait until the implementation is really finished.

**Comment by hassount** [comment]
right now, if you link the latest master and set -rc 0 it will be running crf by default.
