### ISSUE TITLE
R2R found for non multiple of 8 clip for non-lp

### ISSUE THREAD

**Issue by ccccheung** [AOMediaCodec/SVT-AV1#1478]
I have found an R2R in revision 4e2e52b with a clip that has a non-multiple of 8 resolution in both dimensions.
The R2R is found for both 8 bit and 10 bit 
for 8 bit the R2R was observed in M0-M3
for 10bit the R2R was observed in M1-M4

clip parameters:
240 frames
854x478

with lp-1, 
```
./SvtAv1EncApp -enc-mode 4 -q 20  -intra-period  119-enable-tpl-la 1   --lp 1 -i  input_10bit.y4m  -b  output.bin 
```
There is no R2R

However, the same sample command without --lp 1
```
./SvtAv1EncApp -enc-mode 4 -q 20  -intra-period  119-enable-tpl-la 1  -i  input_10bit.y4m  -b  output.bin 
```
There is R2R.

Some experiments I tried were: focusing on the M3 case with 8 bit and M4 case with 10 bit

- Capping the frames encoded at 60 -> no r2r found
- intra-period -1 instead of 119 at full frames -> no r2r found
- intra-period 111 instead of 119 at full frames -> r2r found in M3(8bit) and M4(10 bit)

**Comment by ccccheung** [comment]
This issue seems to be only reproducible when multiple encodings are run in parallel. In this case 25 encodings run with 12 jobs in parallel with no lp option reproduces the r2r

**Comment by spawlows** [comment]
I see few R2R when encoder is run non parallel , and sizes are not multiple by 8 cmd:

````
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 15-out.ivf -enc-mode 5 -w 640 -h 360   -i speed_360p_1minigop.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 24-out.ivf -enc-mode 4 -w 1280 -h 720  -i InToTree_1280x720_8bit_50Hz_P420.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 25-out.ivf -enc-mode 5 -w 1280 -h 720  -i InToTree_1280x720_8bit_50Hz_P420.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 35-out.ivf -enc-mode 5 -w 1920 -h 1080 -i speed_1080p.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 44-out.ivf -enc-mode 4 -w 4096 -h 2160 -i InToTree_1280x720_8bit_50Hz_P420.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 47-out.ivf -enc-mode 7 -w 4096 -h 2160 -i InToTree_1280x720_8bit_50Hz_P420.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 48-out.ivf -enc-mode 8 -w 4096 -h 2160 -i InToTree_1280x720_8bit_50Hz_P420.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 64-out.ivf -enc-mode 4 -w 1280 -h 720  -i UEFA_Euro_2016_Opening_Ceremony_006_1280x720_10bit_50Hz_P420.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 65-out.ivf -enc-mode 5 -w 1280 -h 720  -i UEFA_Euro_2016_Opening_Ceremony_006_1280x720_10bit_50Hz_P420.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 73-out.ivf -enc-mode 3 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 74-out.ivf -enc-mode 4 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 76-out.ivf -enc-mode 6 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 78-out.ivf -enc-mode 8 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv
````

**Comment by OmranAbdelkafi** [comment]
> I see few R2R when encoder is run non parallel , and sizes are not multiple by 8 cmd:
> 
> ```
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 15-out.ivf -enc-mode 5 -w 640 -h 360   -i speed_360p_1minigop.yuv
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 24-out.ivf -enc-mode 4 -w 1280 -h 720  -i InToTree_1280x720_8bit_50Hz_P420.yuv 
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 25-out.ivf -enc-mode 5 -w 1280 -h 720  -i InToTree_1280x720_8bit_50Hz_P420.yuv 
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 35-out.ivf -enc-mode 5 -w 1920 -h 1080 -i speed_1080p.yuv 
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 44-out.ivf -enc-mode 4 -w 4096 -h 2160 -i InToTree_1280x720_8bit_50Hz_P420.yuv 
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 47-out.ivf -enc-mode 7 -w 4096 -h 2160 -i InToTree_1280x720_8bit_50Hz_P420.yuv 
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 8  -b 48-out.ivf -enc-mode 8 -w 4096 -h 2160 -i InToTree_1280x720_8bit_50Hz_P420.yuv 
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 64-out.ivf -enc-mode 4 -w 1280 -h 720  -i UEFA_Euro_2016_Opening_Ceremony_006_1280x720_10bit_50Hz_P420.yuv
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 65-out.ivf -enc-mode 5 -w 1280 -h 720  -i UEFA_Euro_2016_Opening_Ceremony_006_1280x720_10bit_50Hz_P420.yuv
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 73-out.ivf -enc-mode 3 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 74-out.ivf -enc-mode 4 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 76-out.ivf -enc-mode 6 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv
> SvtAv1EncApp.exe -fps 30 -n 400 -pred-struct 0 -bit-depth 10 -b 78-out.ivf -enc-mode 8 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv
> ```

Thanks @spawlows for the information. Is there a reason you are using -pred-struct 0 and did you try the same use cases without that option and see if the r2r still exist ?

**Comment by spawlows** [comment]
Hi @OmranAbdelkafi  I checked without `-pred-struct` and i shure that bellow cmds have R2R issue:

```
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 8 -b  15-out.ivf -enc-mode 5 -w 640 -h 360   -i speed_360p_1minigop.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 8 -b  24-out.ivf -enc-mode 4 -w 1280 -h 720  -i InToTree_1280x720_8bit_50Hz_P420.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 8 -b  25-out.ivf -enc-mode 5 -w 1280 -h 720  -i InToTree_1280x720_8bit_50Hz_P420.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 8 -b  35-out.ivf -enc-mode 5 -w 1920 -h 1080 -i speed_1080p.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 8 -b  44-out.ivf -enc-mode 4 -w 4096 -h 2160 -i InToTree_1280x720_8bit_50Hz_P420.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 8 -b  47-out.ivf -enc-mode 7 -w 4096 -h 2160 -i InToTree_1280x720_8bit_50Hz_P420.yuv 
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 10 -b 64-out.ivf -enc-mode 4 -w 1280 -h 720  -i UEFA_Euro_2016_Opening_Ceremony_006_1280x720_10bit_50Hz_P420.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 10 -b 65-out.ivf -enc-mode 5 -w 1280 -h 720  -i UEFA_Euro_2016_Opening_Ceremony_006_1280x720_10bit_50Hz_P420.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 10 -b 74-out.ivf -enc-mode 4 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 10 -b 76-out.ivf -enc-mode 6 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv
SvtAv1EncApp.exe -fps 30 -n 400 -bit-depth 10 -b 78-out.ivf -enc-mode 8 -w 1920 -h 1080 -i Cactus_10bit_1920x1080_50Hz_P420.yuv

```
