### ISSUE TITLE
--passes 2 with --rc 2 won't work

### ISSUE THREAD

**Issue by z83rulek** [AOMediaCodec/SVT-AV1#1483]
When using :
SvtAv1EncApp -i ADA.y4m -w 1920 -h 1080 --fps-num 24000 --fps-denom 1001 --rc 2 --tbr 4000 --preset 3 --keyint 23 --irefresh-type 2 --passes 2 -b output.ivf

It says :
Error Instance 1: The rate control mode 2/3 LAD must be equal to intra_period
![註解 2020-09-09 040606](https://user-images.githubusercontent.com/21211498/92522747-cfc09900-f251-11ea-8f70-ba9cad479f6f.png)

**Comment by hassount** [comment]
Yes, that combination is not allowed  at this point with 2-pass working only with --rc 0 / 1. we probably need to update the error message

**Comment by hassount** [comment]
@paulsgh can you please look into this: blocking 2-pass VBR when used with --rc 2 / 3 in EbEncHandle.c
