### ISSUE TITLE
Move EbAppString.x files to the third party folder

### ISSUE THREAD

**Issue by hassount** [AOMediaCodec/SVT-AV1#1487]
Move EbAppString.x files to the third party folder as it's license is different

**Comment by hassount** [comment]
@1480c1 can you please look into this ?

**Comment by 1480c1** [comment]
Sure, would it be better to copy the original files from https://github.com/intel/safestringlib/blob/master/safeclib/strncpy_s.c https://github.com/intel/safestringlib/blob/master/safeclib/strcpy_s.c and https://github.com/intel/safestringlib/blob/master/safeclib/strnlen_s.c and prefix the ones in `EbString.c`, set up https://github.com/intel/safestringlib as a cmake submodule that only builds the functions we need, or alternatively just move what we currently have already?

One consideration to note is we have both the `EbString.*` and `EbAppString.*` files that are close in content to each other

**Comment by hassount** [comment]
> s a cmake submodule that only builds the functions we need, or alternatively just move what we currently have already?

sure that works
