### ISSUE TITLE
Allow GOP sizes larger than 256

### ISSUE THREAD

**Issue by veikk0** [AOMediaCodec/SVT-AV1#1492]
Currently, the maximum keyint is 256. This is probably fine for footage that's 30 fps or below as it allows a keyframe interval of up to 10-ish seconds, but for 60 fps and up it starts to run a bit short.

Also, it's a bit counterintuitive that the GOP size is always one larger than the value input with `--keyint`. I.e. `--keyint 60` results in a GOP size of 61.

**Comment by hassount** [comment]
Makes sense to me, @ccccheung can you take a look at this ? @OmranAbdelkafi FYI

**Comment by hassount** [comment]
looking at this further, this cap is also due to a limitation of VBR, being still a WIP. so this would need to be applied to CRF only for now
