### ISSUE TITLE
Hang-up with VBR and "infinite" GOP in v0.8.5 and master (stream and settings specific)

### ISSUE THREAD

**Issue by palexander-14** [AOMediaCodec/SVT-AV1#1499]
There is a hang-up caused by infinte loop in rate control.
(not specific to OS or hardware, macOS 10.14, Windows 10 x64, CentOS 7, Ubuntu 20.04, 6- and 8-core processors were checked)

To be more specific, the encoder stucks in the loop at https://github.com/AOMediaCodec/SVT-AV1/blob/671ffdf865090da4c47ddc7d2ab103a72283c86a/Source/Lib/Encoder/Codec/EbRateControlProcess.c#L666

The issue is specific to settings and input stream.
The command line is:
`SvtAv1EncApp.exe -i "Tears_Of_Steel_1280x720_24_I420_1440_frames.yuv" -w 1280 -h 720 --output out.ivf --rc 1 --tbr 2500 --fps 24 --preset 8 --keyint -1 --frames 300 --lookahead 16 --hierarchical-levels 4`

The link to the input raw file:
https://yadi.sk/d/TYWsK-HUadrKAA

With this combination the encoder hangs after 285 frames.

With different lookahead, hierarchical-levels values there is no hang-up.
With different number of frames to encode there is either a hang on other frame or no hang at all.

As a temporal "hotfix" works the following.
I'm not sure if I got the idea right but
a 100+ lines above in the https://github.com/AOMediaCodec/SVT-AV1/blob/671ffdf865090da4c47ddc7d2ab103a72283c86a/Source/Lib/Encoder/Codec/EbRateControlProcess.c there is a condition that should work in the end of a sequence being encoding:
```
        // For the case that number of frames in the sliding window is less than size of the look ahead or intra Refresh. i.e. end of sequence
        if ((pcs_ptr->frames_in_sw < MIN(scs_ptr->static_config.look_ahead_distance + 1,
                                         (uint32_t)scs_ptr->intra_period_length + 1))
```
In this particular case this condition never works because `(uint32_t)scs_ptr->intra_period_length + 1 == 0`.
So to make this condition working in the end of a stream the following changes were made:
```
        // For the case that number of frames in the sliding window is less than size of the look ahead or intra Refresh. i.e. end of sequence
        const uint32_t intra_period_length_plus1 = 
            (scs_ptr->intra_period_length == -1) ? 0x0FFFFFFFU
            : (uint32_t)scs_ptr->intra_period_length + 1;

        if ((pcs_ptr->frames_in_sw < MIN(scs_ptr->static_config.look_ahead_distance + 1,
                                         intra_period_length_plus1)))
```

P.S. Not so much testing were made with these changes. And I'm just sharing, may be this will help somehow )

**Comment by hassount** [comment]
@OmranAbdelkafi can we take a look at this ?

**Comment by palexander-14** [comment]
A little update.
I've checked the originally reported command line with option enable_tpl_la disabled. It hangs as well.

**Comment by kelvinhu325** [comment]
Hi @xudongxu135 , I can not get hang on my linux machine with latest master code commit 9ca833328c76bafff20736054a45210b2d8ea0f5 , what's the "version of 0.8.5 #1584"?

**Comment by hassount** [comment]
@palexander-14 can you please check if the latest master addressed the issue ?

**Comment by palexander-14** [comment]
Checked with a5ec26c0f0bd6e872a0b2bb340b4a777f4847020
No hang-up with originally reported command line but there is new rare (1 time out of 10) with the following command line:
`SvtAv1EncApp.exe -i "Tears_Of_Steel_1280x720_24_I420_1440_frames.yuv" -w 1280 -h 720 --output out.ivf --rc 1 --tbr 2500 --fps 24 --preset 8 --keyint -1 --frames 1300 --lookahead 16 --hierarchical-levels 4 --progress 2`

The hang is in the loop https://github.com/AOMediaCodec/SVT-AV1/blob/a5ec26c0f0bd6e872a0b2bb340b4a777f4847020/Source/Lib/Encoder/Codec/EbRateControlProcess.c#L1878
In some cases lookahead can return the same predicted bits for two adjacent qp values. And the condition at https://github.com/AOMediaCodec/SVT-AV1/blob/a5ec26c0f0bd6e872a0b2bb340b4a777f4847020/Source/Lib/Encoder/Codec/EbRateControlProcess.c#L1956 is composed in way that cannot "pick" the only value.

For testing purposes I have modified this condition so it picks minimal of two adjacent qp value candidates:
```
                const uint64_t la_bit_distance_temp = (uint64_t)ABS(
                    (int64_t)high_level_rate_control_ptr->pred_bits_ref_qp_per_sw[ref_qp_index] - (int64_t)bit_constraint_per_sw);
                if (min_la_bit_distance >= la_bit_distance_temp) {
                    if (min_la_bit_distance == la_bit_distance_temp && ref_qp_index < selected_ref_qp)
                        best_qp_found = EB_TRUE;
                    min_la_bit_distance = la_bit_distance_temp;
                    selected_ref_qp     = ref_qp_index;
                } else
                    best_qp_found = EB_TRUE;
```

There's no hang with these changes

**Comment by paulsgh** [comment]
Using 42c1213 on Linux, I tested:

- the original cmd line: `./SvtAv1EncApp -i "Tears_Of_Steel_1280x720_24_I420_1440_frames.yuv" -w 1280 -h 720 --output out.ivf --rc 1 --tbr 2500 --fps 24 --preset 8 --keyint -1 --frames 300 --lookahead 16 --hierarchical-levels 4`
- new cmd line (20 runs): `./SvtAv1EncApp -i "Tears_Of_Steel_1280x720_24_I420_1440_frames.yuv" -w 1280 -h 720 --output out.ivf --rc 1 --tbr 2500 --fps 24 --preset 8 --keyint -1 --frames 1300 --lookahead 16 --hierarchical-levels 4 --progress 2`

I was unable to reproduce a hang with either cmd line.
