### ISSUE TITLE
Multi-rate encoding

### ISSUE THREAD

**Issue by veikk0** [AOMediaCodec/SVT-AV1#1502]
Since SVT-AV1 seems to be aimed primarily at VOD use cases at the moment, and one of the bigger challenges for AV1 adoption is encoding speed, supporting multi-rate encoding (reuse of analysis information between multiple resolution and bitrate encodes of the same content) seems like something that could be very beneficial to many users.

According to [this Demuxed 2018 presentation](https://www.youtube.com/watch?v=-yPOE2F9fDI) by Alex Giladi, x265's multi-rate encoding feature (documentation for which can be found [here](https://x265.readthedocs.io/en/master/cli.html#abr-ladder-options) and [here](https://x265.readthedocs.io/en/master/cli.html#cmdoption-analysis-save-reuse-level)) is able to speed up the encoding of 2160p UHD content by up to 2.43x with no quality loss. See 5m38s of the presentation for the exact results. According to his summary, this approach could be implemented for any codec, including AV1.

I'd be interested to know whether it would be practical to implement something like this for SVT-AV1.

**Comment by hassount** [comment]
@veikk0 thank you for the details and the additional information. It's indeed a good opportunity to save on cycles and potentially other optimizations. While this is not a short term projects we could potentially be looking into this after the optimizations for speed and quality are done on the presets.

we'll use this issue to track
