### ISSUE TITLE
Color space signaling; full-range vs restricted range

### ISSUE THREAD

**Issue by jonsneyers** [AOMediaCodec/SVT-AV1#1505]
Currently, the encoder is always signaling that the YCbCr values are using restricted range (16..235) and not full range (0..255). Is there a specific reason for this? For 8-bit encoding, using full range helps a little bit to avoid color banding.

**Comment by hassount** [comment]
a great opportunity for contributions!

**Comment by lextra2** [comment]
Maybe add internal dithering to 0-255 full range (for increased encoder accuracy) and finish to 16-235 limited if the input was limited to begin with.
