### ISSUE TITLE
Encoder crashes in master and v0.8.5 when look ahead distance is more than 60 frames and enable_tpl_la is on

### ISSUE THREAD

**Issue by palexander-14** [AOMediaCodec/SVT-AV1#1507]
There is a crash on long look ahead (more than 60 frames) when option enable_tpl_la == 1.
The crash happens on all platforms. On Windows for example it is an excpetion 0xc0000409 (STATUS_STACK_BUFFER_OVERRUN).
Command line:

`SvtAv1EncApp.exe -i "in_file.yuv" -w 1280 -h 720 --output "out.ivf" --rc 1 --tbr 2500 --fps 60 --preset 8 --keyint 60 --frames 300 --pred-struct 2 --hierarchical-levels 4 --irefresh-type 1 --lookahead 120`

Resolution, GOP length and other parameters are unrelated.

Quick investigation shows that the happens when look_ahead_distance is more than `MAX_TPL_LA_SW` defined as 60:
https://github.com/AOMediaCodec/SVT-AV1/blob/8e7806fde7c65f74d115d4b3a4ef0b68b0aaea67/Source/Lib/Common/Codec/EbDefinitions.h#L46

If `MAX_TPL_LS_SW` is redefined to 90 for example then the encoder crashes on look_ahead_distance > 90.

So, for me it worked to define `MAX_TPL_LA_SW` to `MAX_LAD + 1`
`#define MAX_TPL_LA_SW MAX_LAD + 1 // Max TPL look ahead sliding window size`

**Comment by palexander-14** [comment]
But it turned out that after applying the patch mentioned above the encoder hangs sometimes with different parameters.
And these hangs are very similar to https://github.com/AOMediaCodec/SVT-AV1/issues/1499

**Comment by hassount** [comment]
@palexander-14 
right now, the max lookahead that TPL allows is 16 so it is expected that the code would not work properly if that changes. usually, if the parameter is not controlled by a run-time flag and is set by a MACRO inside the code, it means that the value has to be the one specified for now. the ```MAX_LAD``` macro is also used for --rc 1/2 thus the reason of setting a different one for ```MAX_TPL_LA_SW ```

**Comment by palexander-14** [comment]
Thanks for clarification, @hassount 

But it seems to me that the settings "validator" should be updated somehow (as well as the function which automatically calculates default value for the look ahead distance).
Right now the following command line leads to the crash:
`SvtAv1EncApp.exe -i "in_file.yuv" -w 1280 -h 720 --output "out.ivf" --rc 1 --tbr 2500 --fps 90`
becasue the enable_tpl_la option is enabled by default, but default look ahead distance is higher than 60.

Also it was noticed that it's impossible to encode 120 fps video with default LAD:
`SvtAv1EncApp.exe -i "in_file.yuv" -w 1280 -h 720 --output "out.ivf" --rc 1 --tbr 2500 --fps 120`
The encoder shows the following error in this case:
`Error Instance 1: The lookahead distance must be [0 - 120]`

**Comment by hassount** [comment]
> Thanks for clarification, @hassount
> 
> But it seems to me that the settings "validator" should be updated somehow (as well as the function which automatically calculates default value for the look ahead distance).
> Right now the following command line leads to the crash:
> `SvtAv1EncApp.exe -i "in_file.yuv" -w 1280 -h 720 --output "out.ivf" --rc 1 --tbr 2500 --fps 90`
> becasue the enable_tpl_la option is enabled by default, but default look ahead distance is higher than 60.
> 
> Also it was noticed that it's impossible to encode 120 fps video with default LAD:
> `SvtAv1EncApp.exe -i "in_file.yuv" -w 1280 -h 720 --output "out.ivf" --rc 1 --tbr 2500 --fps 120`
> The encoder shows the following error in this case:
> `Error Instance 1: The lookahead distance must be [0 - 120]`

good points, definitely something to be looked into, enable_tpl_la should not be enabled for rc > 0 already that's an issue.
