### ISSUE TITLE
mismatch between bitstreams generated by ffmpeg and by SVT-AV1 encoder app

### ISSUE THREAD

**Issue by ccccheung** [AOMediaCodec/SVT-AV1#1510]
I have tried encoding the same set of clips using libsvtav1 via ffmpeg and the SVT-AV1 encoder app and found that the bitstreams produced by the two do not match.

The clip set I tested was a subset of the obj-1 fast 8bit set with presets M0, M4, and M8. 

Since the ffmpeg wrapper doesn't expose most of the command line options, I had to match up the parameters on the encoder app's side to the defaults set by the library. After doing so, there is only a mismatch left in the IVF header for most clips (svt av1 encoder app doesn't populate number of frames field, ffmpeg reduces the framerate fraction) 

The exception is with gipsrestat, which shows a mismatch in the encoded picture content

It seems with gipsrestat, the ffmpeg plugin encodes 61 frames instead of 60 frames. Furthermore, even though both have loop filter enabled, only the ffmpeg encoder appears to apply it to the first frame. When both bitstreams are decoded, the ffmpeg bitstream does not match the original source .yuv.

@1480c1  has mentioned to me this may be due to a mismatch in how ffmpeg handles receiving packets vs how svt-av1 encoder app handles it.

**Comment by hassount** [comment]
@xuguangxin can you take a quick look at the ffmpeg mismatch causing an extra frame to be encoded ? 
@1480c1 can we add a ci test to make sure that these would always match ? encode / decode compare yuvs.

**Comment by 1480c1** [comment]
For the mismatch test, do you want the comparison to be while it's an ivf or after decoding to yuv or both?

**Comment by hassount** [comment]
> For the mismatch test, do you want the comparison to be while it's an ivf or after decoding to yuv or both?

well it seems that the IVF comparison would produce a mismatch due to the way the headers are handled. so yuvs for now ?>

**Comment by ccccheung** [comment]
Other clips in the obj-1 fast 8 bit set that shows the same kind of mismatch as gipsrestat:
DOTA_2
ducks_take_off
KristenAndSara
MINECRAFT
Netflix_Aerial
Netflix_Boat
Netflix_Crosswalk
Netflix_DrivingPOV
Netflix_FoodMarket
Netflix_PierSeaside
Netflix_RollerCoaster
Netflix_SquareAndTimelapse
Netflix_TunnelFlag
shields
STARCRAFT
vidyo1
vidyo4

**Comment by xuguangxin** [comment]
@ccccheung which comandline you used. I encoded 60 frames, dav1d reported 60 frames.

$ ./ffmpeg -i 128x128_60f.y4m -c:v libsvtav1 test.ivf
ffmpeg version N-99257-g01506c290a Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --enable-gpl --enable-shared --prefix=/myopt/codecs/vaapi --disable-stripping --disable-optimizations --enable-debug=3 --disable-asm --enable-libsvtav1 --enable-libdav1d
...
**frame=   60** fps= 21 q=46.0 Lsize=       7kB time=00:00:02.40 bitrate=  23.9kbits/s speed=0.83x
video:6kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 11.700638%
SvtMalloc[info]: you have no memory leak

$ ./ffmpeg -i  test.ivf -f null -
...
[libdav1d @ 0x5634f7d5e3c0] libdav1d 0.7.1-66-g8c2a897
Stream mapping:
  Stream #0:0 -> #0:0 (av1 (libdav1d) -> wrapped_avframe (native))
Press [q] to stop, [?] for help
Output #0, null, to 'pipe:':
  Metadata:
    encoder         : Lavf58.56.100
    Stream #0:0: Video: wrapped_avframe, yuv420p, 128x128 [SAR 1:1 DAR 1:1], q=2-31, 200 kb/s, 25 fps, 25 tbn, 25 tbc
    Metadata:
      encoder         : Lavc58.106.100 wrapped_avframe
**frame=   60** fps=0.0 q=-0.0 Lsize=N/A time=00:00:02.40 bitrate=N/A speed= 104x
video:31kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

**Comment by ccccheung** [comment]
@xuguangxin I tried it with the y4m versions and they seem to encode 60 frames. 

But using yuv and the following command line
```./ffmpeg -s:v 1920x1080 -pix_fmt yuv420p -r 60000/1000 -i Netflix_Aerial_1920x1080_60fps_8bit_420_60f.yuv -qp 63 -preset 8 -c:v libsvtav1 -y output.ivf```

I get the following as output
```Output #0, ivf, to 'output.ivf':
  Metadata:
    encoder         : Lavf58.58.100
    Stream #0:0: Video: av1 (libsvtav1) (AV01 / 0x31305641), yuv420p, 1920x1080, q=0-63, 7000 kb/s, 60 fps, 60 tbn, 60 tbc
    Metadata:
      encoder         : Lavc58.106.100 libsvtav1
frame=   61 fps= 11 q=61.0 Lsize=      77kB time=00:00:01.01 bitrate= 618.2kbits/s dup=1 drop=0 speed=0.188x
video:76kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.982018%
```
And the following output from libdav1d:
```
[libdav1d @ 0x6aca200] libdav1d 0.7.0-21-g07261e8
Stream mapping:
  Stream #0:0 -> #0:0 (av1 (libdav1d) -> wrapped_avframe (native))
Press [q] to stop, [?] for help
Output #0, null, to 'pipe:':
  Metadata:
    encoder         : Lavf58.46.101
    Stream #0:0: Video: wrapped_avframe, yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 60 fps, 60 tbn, 60 tbc
    Metadata:
      encoder         : Lavc58.92.100 wrapped_avframe
frame=   61 fps=0.0 q=-0.0 Lsize=N/A time=00:00:01.01 bitrate=N/A speed=9.83x
video:32kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
```

**Comment by xuguangxin** [comment]
@ccccheung this is a ffmpeg issue. It will generate 61 frames even without the svt av1 encoder. 

> ffmpeg -r 60000/1000 -s 128x128 -i 128x128_60f.yuv test.y4m
> ...
> frame=   **61** fps=0.0 q=-0.0 Lsize=    1464kB time=00:00:01.01 bitrate=11799.8kbits/s dup=1 drop=0 speed=86.9x
> video:32kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 4486.371582%
> 

you can use -vsync 0 to get 60 frames. 
exmaple comand line is:

> $ffmpeg -r 60000/1000 -s 128x128 -i 128x128_60f.yuv -c:v libsvtav1 out.ivf -y **-vsync 0**
> ...
> frame=   ****60**** fps= 29 q=50.0 Lsize=       4kB time=00:00:01.00 bitrate=  31.3kbits/s speed=0.476x
> video:3kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 23.774897%
> SvtMalloc[info]: you have no memory leak

**Comment by xav1vfw** [comment]
EbEncHandle.c -> eb_svt_enc_init_parameter() is not complete yet, these settings are missing yet (they were set in the encoder app):
config_ptr->vbr_bias_pct = 50;
config_ptr->vbr_min_section_pct = 0;
config_ptr->vbr_max_section_pct = 2000;
config_ptr->under_shoot_pct = 25;
config_ptr->over_shoot_pct = 25;

**Comment by xuguangxin** [comment]
@xav1vfw , since https://github.com/AOMediaCodec/SVT-AV1/pull/1524 is merged. 
we have the single point to init the configuration. could you help add these code to eb_svt_enc_init_parameter?
thanks

**Comment by xav1vfw** [comment]
It seems I have no rights/access to push/commit anything into svt-av1 git repo...

**Comment by hassount** [comment]
> It seems I have no rights/access to push/commit anything into svt-av1 git repo...

yes, that is expected, you'd need to create a pull request for your contribution to be evaluated by ci and reviewed before being merged

**Comment by xav1vfw** [comment]
> 
> yes, that is expected, you'd need to create a pull request for your contribution to be evaluated by ci and reviewed before being merged

Done in #1542

**Comment by hassount** [comment]
Closing this as I believe the rest is more an ffmpeg issue
