### ISSUE TITLE
SVT Crash in UGC Long Clip

### ISSUE THREAD

**Issue by paulsgh** [AOMediaCodec/SVT-AV1#1523]
## Description:
We have found a crash in one of the UGC clips.
- **encoder:** svt
- **qp:** 55
  - of the 5 QPs we normally use for BD-Rate (20, 32, 43, 55, 63), only 55 had the crash
- **revision:** master@c9f697a
- **clip:** Vertical_MobileGaming_1080p.y4m
- **number of frames in clip:** 580

The crash happens after encoding approximately 200 frames.

## Sample Command Line:
`(/usr/bin/time --verbose   ./SvtAv1EncApp -enc-mode 0 -q 55  -intra-period  -1  -enable-tpl-la 1  -lp 1  -i  /home/ubuntu/stream/UGC_selection_y4m_clipped/Vertical_MobileGaming_1080p.y4m  -b  bitstreams/svt_M0_Vertical_MobileGaming_1080p_Q55.bin )  > bitstreams/svt_M0_Vertical_MobileGaming_1080p_Q55.txt 2>&1`

## Initial Debugging:
- problem only happens in M0 
- tried to box the issue between M0 and M1
  - using M1 settings for the following features led to the disappearance of the issue:
    - SQ_WEIGHT
    - TXS_IN_INTER_CLASSES
    - SEARCH_AREA
- since M0 to M1 debugging was inconclusive, we tried to box the issue by bisecting the commits, as tag v0.8.5 didn't have the crash
  -  breaking commit: 40b661e
- also tested `-enable-tpl-la 0 -lad 0`
  - no issue detected in this case

**Comment by tszumski** [comment]
Hi,
I I checked your command line and for current master ab027d1ca74882e3e058b7e9b7ed1877e4b9ee4a I don't see any crash.
This issue is fixed by PR #1520

**Comment by hassount** [comment]
> Hi,
> I I checked your command line and for current master [ab027d1](https://github.com/AOMediaCodec/SVT-AV1/commit/ab027d1ca74882e3e058b7e9b7ed1877e4b9ee4a) I don't see any crash.
> This issue is fixed by PR #1520

@tszumski thank you, @paulsgh can you confirm ?

**Comment by paulsgh** [comment]
Thanks @tszumski.
@hassount I ran the command line with current master 000b0fa, and can confirm it does not crash. I will follow up to confirm there is no crash using the command line with PR1520 MOD 00f2e74.

**Comment by hassount** [comment]
great thank you.
