### ISSUE TITLE
Add/port Arm64 NEON assembly

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/SVT-AV1#1527]
Both rav1e and libaom (and dav1d) use NEON assembly to speedup functions on 64-bit Arm (AArch64). It would be great if SVT-AV1 could also speedup the most CPU intensive functions with NEON assembly. Probably a lot can be ported.

Here's the NEON assembly in libaom, rav1e and dav1d:
- [libaom](https://aomedia.googlesource.com/aom/+/master/aom_dsp/arm)
- [rav1e](https://github.com/xiph/rav1e/tree/master/src/arm/64)
- [dav1d](https://code.videolan.org/videolan/dav1d/-/tree/master/src/arm/64)

**Comment by Vargol** [comment]
Why has thius been  closed as the NEON code been added, I can't see it in the git repository.

**Comment by hassount** [comment]
This repo has moved to gitlab since Feb of last year. This repo is now just a mirror. 
you can find this issue on gitlab:

https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues/1527
