### ISSUE TITLE
Add ability to use CRF / CQ on faster presets

### ISSUE THREAD

**Issue by Felixkruemel** [AOMediaCodec/SVT-AV1#1536]
Currently I'm not able to use CRF with 2 pass on e.g. preset 6 in the second pass. Would be great to have that too!

**Comment by hassount** [comment]
You can still use CRF with lookahead in 1 pass mode. Is there a specific ask for 2-pass in this case ?

**Comment by Felixkruemel** [comment]
@hassount Could you give an command-line example for that?

I just want to not rely on a fixed QP, but on crf or cq (like in aomenc).

1pass would be totally fine as long as it works properly, I just didn't knew about this method before.

**Comment by hassount** [comment]
@Felixkruemel yes, I see that the description would now need to be updated in the users guide. But basically the commandline is the one used here:
https://github.com/AOMediaCodec/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.md#1-pass-fixed-qp-at-maximum-speed-from-24fps-yuv-1920x1080-input

SvtAv1EncApp -i input.y4m --rc 0 -q <initial qp level 0-63> --enable-tpl-la 1 --preset <preset> -b output.ivf

Is the 1-pass crf which should work well for all presets now.

**Comment by Felixkruemel** [comment]
Okay, thanks a lot @hassount 

If you could update the docu it would be great! And examples are always appreciated :)

**Comment by Felixkruemel** [comment]
@hassount Is there also a way to use crf in ffmpeg through libsvtav1?

**Comment by hassount** [comment]
Yes the default command line with -rc 0 would yield in crf working

**Comment by Felixkruemel** [comment]
@hassount So specify the quality setting with -qp then? Seems to be somewhat misleading.

**Comment by hassount** [comment]
Yes qp is the initial qp level in this case. I agree that linking crf here would be much better
