### ISSUE TITLE
Using "--irefresh-type 1" (open gop) results in video that has poor seeking performance in all web browsers and various media players

### ISSUE THREAD

**Issue by Neltulz** [AOMediaCodec/SVT-AV1#1548]
**What steps will reproduce the problem?**
1. Download the included y4m file in 7z file (Extract it)  https://www.dropbox.com/s/m7vu0eycpjd47aq/Ted_2012_REMUX_SAMPLE.y4m_EXTRACT_ME.7z?dl=0
2. Using SvtAv1EncApp.exe (SVT [version]:  SVT-AV1 Encoder Lib v0.8.5-39-g3fbd1ee9) (SVT [build]  :  GCC 10.2.0       64 bit) (LIB Build date: Sep 30 2020 19:30:58)
3. encode using these settings:

``
SvtAv1EncApp.exe --irefresh-type 1 --keyint 48 -q 25 -b Ted_2012_SAMPLE_av1-svt_irefresh-type-1_keyint-48.ivf -i Ted_2012_REMUX_SAMPLE.y4m
``

4. Using MKVToolnix version 51.0.0.0, drag drop the .ivf file onto the MKVToolNix GUI, rename the output from .mkv to .webm (this will automatically enable webm compatability mode), then save the file as a .webm  You may download mkvtoolnix here: https://mkvtoolnix.download/downloads.html

5. (Optional) Upload the WebM to web server of your choosing

6.  If skipped step 5, drag drop the WebM onto Google Chrome to open the video in a new tab.
     If **NOT** skipped step 5, open the URL of the WebM file in Google Chrome.  Here is a URL for your convenience: http://logichaos.com/neil_tmp/ted_sample_bug_report_svtav1/Ted_2012_SAMPLE_av1-svt_irefresh-type-1_keyint-48.webm

7. Click anywhere on the seekbar to seek to a position of your choosing.  If you click closer towards the beginning, the video will seek fairly quickly.  If you click closer towards the end of the video, the video will take a long time to seek (presumably because the video is decoding from the beginning of the video, and not the nearest keyframe).

8. You may compare to this video, which uses ``--irefresh-type 2`` (closed gop)
http://logichaos.com/neil_tmp/ted_sample_bug_report_svtav1/Ted_2012_SAMPLE_av1-svt_irefresh-type-2_keyint-48.webm

9. Click anywhere on the seekbar to seek to a position of your choosing.  You will notice that seeking performance is dramatically improved.

10.  You may test this on longer sample videos to see the problem amplified.  If using ``--irefresh-type 1`` (open gop) -- the longer the sample, the longer it will take for the video to seek to the position.

**What is the expected output?**
- User should be able to click anywhere on the seek bar and be able to seek to that position without any issues.

**What do you see instead?**
- Poor seeking performance when user clicks anywhere on the seek bar, but the performance is worse if the user clicks closer towards the end of the video.

**Tested in:**
- Windows 10 Pro 64bit
- Edge Chromium Version 86.0.622.48 (Official build) (64-bit)
- Google Chrome 
- Firefox 82.0 (64-bit)
- Firefox Nightly 84.0a1 (2020-10-24) (64-bit)
- MPV.net version 5.4.8.0
- MPC-BE version 1.5.5 x64
- VLC Portable version 3.0.11 Vetinari

All of the tested applications have difficulty seeking.

**Please provide any additional information below.**
- Using "--irefresh-type 2" always results in a file that is able to properly seek properly without any issues;
  therefore: the issue is limited to ``--irefresh-type 1``

This works great every time, able to seek with no issues what-so-ever:
http://logichaos.com/neil_tmp/ted_sample_bug_report_svtav1/Ted_2012_SAMPLE_av1-svt_irefresh-type-2_keyint-48.webm

This one has problem with seeking, poor performance, or complete refusal to seek (already linked this one above in the step by step process):
http://logichaos.com/neil_tmp/ted_sample_bug_report_svtav1/Ted_2012_SAMPLE_av1-svt_irefresh-type-1_keyint-48.webm

Please note, that I have also opened a similar issue for aomenc regarding poor seeking performance.  Perhaps this issue is related.  I highly advise checking out this issue and reading the comments from the project members.  Hopefully a solution can be found. https://bugs.chromium.org/p/aomedia/issues/detail?id=2862

**Comment by Neltulz** [comment]
It is my opinion that until this issue has been resolved, the encoder should default to ``--irefresh-type 2`` (closed gop) so that web browsers and various media players have adequate time to resolve this issue from the decoding side.

**Comment by hassount** [comment]
@Neltulz thank you for the detailed report an the thorough explanation. using  ```--irefresh-type 1``` allows the encoder to insert a forward frame which does not reset the decoding order. Using ```--irefresh-type 2``` does reset the decoding order thus the ability to see faster throughout the clip. Using a more sophisticated app than the SVT sample application, the user can set Keyframes at a larger intervals and forward frame at some shorter interval to reduce the error propagation. 
This is not an issue rather the way that the different intra frame types are supposed to work.

**Comment by Neltulz** [comment]
Okay, I'll be honest, I am not the most technically inclined person.  So, some of what you said didn't make perfect sense.  I'm here for the simple purpose of informing you that the default option of ``--irefresh-type 1`` results in videos with poor seeking, so that you will modify your encoder to have more appropriate default settings, so that people who use your sample encoder, produce videos that seek properly.  It's my opinion that, every video encoder should have default settings that produce videos without issues, **especially** since AV1 is being heavily pushed now by both big industry and community.

Here are some additional videos I encoded.  This time, instead of specifying a keyframe interval, I left it at the default value of ``-1``:

30 second sample with Open Gop resulting in poor seekability especially if you click towards the end: https://www.logichaos.com/neil_tmp/ted_sample_bug_report_svtav1/holy_shit_sugarcane_2020-10-20_640x360_30fps_10bit_av1-svt_cq25_keyint_-1_irefresh-type-1-opengop.webm


30 second sample with Closed Gop resulting in great seekability: https://www.logichaos.com/neil_tmp/ted_sample_bug_report_svtav1/holy_shit_sugarcane_2020-10-20_640x360_30fps_10bit_av1-svt_cq25_keyint_-1_irefresh-type-2-closedgop.webm

2 minute, 33 second sample with open gop resulting in poor seekability especially if you click towards the end:
https://www.logichaos.com/neil_tmp/ted_sample_bug_report_svtav1/batman_640x264_23-976fps_10bit_av1-svt_cq40_keyint_-1_irefresh-type-1-opengop.webm

2 minute, 33 second sample with closed gop resulting in great seekability:
https://www.logichaos.com/neil_tmp/ted_sample_bug_report_svtav1/batman_640x264_23-976fps_10bit_av1-svt_cq40_keyint_-1_irefresh-type-2-closedgop.webm

The point I am making is, if people without the "more sophisticated app" use the SVT-AV1 encoder to produce videos (i.e. in programs such as StaxRip) with default settings, they will be unknowingly creating videos with poor seekability out-of-box due to SVT-AV1's default settings.

By providing a sample encoder, you have to assume that people will be using it with "unsophisticated apps", or no app at all, just straight up using the SVT-AV1 sample encoder, then you should consider the impact it is having across the planet.  People are using it to create videos that have seekability problems.

You can solve this right now just by making ``--irefresh-type 2`` (closed gop) the default setting, and then putting a caution on ``irefresh-type 1`` (open gop).

Why not just do that?  I'm not asking for much.

People use this encoder already.  If this is not an issue, then why is it clearly an issue?

**Comment by silverbacknet** [comment]
This is more of a decoder/parser bug than an encoder deficiency, and an fixed ffmpeg will probably make the problem go away, but it is still pretty universal in past encoders that closed gop is default and open gop optional.

**Comment by Neltulz** [comment]
> This is more of a decoder/parser bug than an encoder deficiency, and a fixed ffmpeg will probably make the problem go away, but it is still pretty universal in past encoders that closed gop is default and open gop optional.

Hi, thanks for adding a bit more info to this.

So, I think ffmpeg making the problem go away is still very much a band-aid.  That will reduce the amount of encodes with poor seekability quite a bit, since ffmpeg is very very popular.  However, there are still lots of applications out there that will not go through ffmpeg.  For instance, StaxRip does not appear to do that.

So, what I propose, will resolve the issue across the board, and in my honest opinion, that is the way to go since it can accomplish the most success with the least amount of work without placing much of the burden on others (at least initially).  Eventually players will have to properly support Open GOP.  That problem can be tackled slowly over time.

**Comment by hassount** [comment]
Alright so the request here is to have closed gop be set by default, I believe it's the case in ffmpeg already, but this can be propagated to the SVT sample application. @Neltulz would you like to create a PR to do such ? basically changing this line of code: 

https://github.com/AOMediaCodec/SVT-AV1/blob/d5ad67725b0190615eef35897acfc0fa0c73a08f/Source/Lib/Encoder/Globals/EbEncHandle.c#L2916

and updating the documentation accordingly.
