### ISSUE TITLE
[ffmpeg] Memory issue

### ISSUE THREAD

**Issue by Felixkruemel** [AOMediaCodec/SVT-AV1#1549]
When I use ffmpeg with -rc 0 -qp 23 -preset 6 it hugs the memory. After roughly an hour into encoding it uses around 20GB of RAM for me, once it reaches the system limit it just won't encode anylonger. Don't know what to do then splitting all video files into 20min chunks.

I've compiled ffmpeg yesterday and I'm running on Windows 10 2004.

**Comment by hassount** [comment]
What resolution are you using ? you could try using the --lp setting of the SvtAv1EncApp that allows you to reduce the memory being used towards targeting a lower amount of cores on the machine.

**Comment by Felixkruemel** [comment]
@hassount It's 1080p only.

The thing is that it worked like 2 weeks ago with an older build. Don't know what happend since then. 
And I think 1080p encoding shouldn't use more than 20GB of memory. 

If there's a way to provide logs I'm happy to do that.

**Comment by hassount** [comment]
This is weird then, and 20 GB for 1080p seems too large unless you’re using a large server. Would you be able to share some logs + the info of the system?

**Comment by Felixkruemel** [comment]
@hassount How can I get logs from ffmpeg?
It's running on an Ryzen 7 3700X, 32GB RAM

**Comment by lextra2** [comment]
> 
> 
> @hassount How can I get logs from ffmpeg?
> It's running on an Ryzen 7 3700X, 32GB RAM

Use `-report`
Example:
`ffmpeg -report -i input.webm -c:v libx264 output.mkv`

**Comment by Felixkruemel** [comment]
@lextra2 @hassount 
Okay there you go:
![grafik](https://user-images.githubusercontent.com/12109804/97335888-a77f0f00-187e-11eb-8e8f-83312c24e547.png)

And the log:
https://gist.githubusercontent.com/Felixkruemel/f1bc037eee1212afb3879282d8697eef/raw/1ae01944e947865ea810f6bced6718af2c2f4a87/gistfile1.txt

Hopefully that helps.
I closed encoding in between as it would break due to memory usage so or so.

**Comment by hassount** [comment]
> @lextra2 @hassount
> Okay there you go:
> ![grafik](https://user-images.githubusercontent.com/12109804/97335888-a77f0f00-187e-11eb-8e8f-83312c24e547.png)
> 
> And the log:
> https://gist.githubusercontent.com/Felixkruemel/f1bc037eee1212afb3879282d8697eef/raw/1ae01944e947865ea810f6bced6718af2c2f4a87/gistfile1.txt
> 
> Hopefully that helps.
> I closed encoding in between as it would break due to memory usage so or so.

Thank you @Felixkruemel  I don't really see libsvtav1 being invoked in this case, am I missing something ?

**Comment by Felixkruemel** [comment]
@hassount 
5th line in the log:
ffmpeg -i input.mkv -report **-vcodec libsvtav1** -rc 0 -qp 22 -preset 6 -acodec copy -scodec copy output.mkv

It works with other encoders, so needs to be some really specific problem here.

**Comment by hassount** [comment]
@Felixkruemel refreshing this, is this still an issue after 0.8.6 ?

**Comment by Felixkruemel** [comment]
@hassount I haven't experienced the issue in the last month. So I guess no, can be closed.
