### ISSUE TITLE
[Feature Request] FFmpeg passtrhough HDR10 static metadata

### ISSUE THREAD

**Issue by cdgriffith** [AOMediaCodec/SVT-AV1#1553]
It would be great to be able to set Mastering display metadata and Content light level metadata via FFmpeg similar to `x265-params` and their `master-display` and `max-cll`

Suggested method would be a `svtav1-params`  (as multiple libraries accept params this way, such as `x265-params` or `rav1e-params` )

Example:
```
-svtav1-params "master-display=G(8500,39000)B(6000,2300)R(30000,14000)WP(15000,16400)L(40000000,50):max-cll=0,0"
```

Another method could be adding two separate new keys, `-master-display` and `-max-cll`

**Comment by quietvoid** [comment]
Perhaps CLI arguments or an API to pass them would be better implemented first.
Currently there is --hdr but it does nothing as far as I know.
