### ISSUE TITLE
[Feature Request] Add a key=value API inside the library

### ISSUE THREAD

**Issue by 1480c1** [AOMediaCodec/SVT-AV1#1555]
It would be nice to have something like a `key=value` API inside the library so it will be possible to set extra values and configuration parameters through said API instead of needing to expose and set individual switch and parameters through a struct on the application side.

This is based on some mention about how adding something similar to {x264,x265,rav1e}-params currently in ffmpeg for libaom would help instead of needing to add each new flags from aomenc to ffmpeg

https://patchwork.ffmpeg.org/project/ffmpeg/patch/20201027203815.131648-1-bohanli@google.com/

**Comment by 1480c1** [comment]
libaom's issue https://bugs.chromium.org/p/aomedia/issues/detail?id=2875

**Comment by SebastianGode** [comment]
@1480c1 libaom has added that feature now.
Would be great to have that here too
