### ISSUE TITLE
Inconsistent encoding results

### ISSUE THREAD

**Issue by itaibenari** [AOMediaCodec/SVT-AV1#1556]
It looks like encoding a file several times might result in inconsistent results.
I've [attached](https://github.com/AOMediaCodec/SVT-AV1/files/5464358/test.zip) a program that reads a jpeg and encodes it several times until the size of the output differs from the initial encoding. I couldn't yet find an image for which it doesn't stop after ~20 iterations at the most. Usually sooner.
For this [image](https://user-images.githubusercontent.com/498228/97693522-f8268000-1aa9-11eb-8620-39ae181f67ca.jpg) - first iteration completes fine. 2nd iteration fails with
```dev/src/SVT-AV1/Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c:1157: generate_r0beta: Assertion `beta > 0.0' failed.```

Thanks!

**Comment by hassount** [comment]
@itaibenari can you please share the command line used to get the failure ? 
and are you trying to pass a jpeg image or are you converting it to yuv ?

**Comment by itaibenari** [comment]
@hassount sure. on a linux machine first run `make`. then
```
./test path/to/image.jpg
```
the code loads the jpeg into YUV (YCbCr) once, and then feeds it in each iteration to the encoding process.

**Comment by itaibenari** [comment]
hey @hassount any news on that? more info which is needed?

**Comment by hassount** [comment]
> hey @hassount any news on that? more info which is needed?

@itaibenari thank you for the additional info, I see that you built your own application to drive the library, in order to box this further, were you able to see this issue using the SVT-AV1 sample app or ffmpeg ?

**Comment by itaibenari** [comment]
@hassount My example code is targeted at producing AVIFs.
Using ffmpeg I didn't come across inconsistent results, but this was when using an invocation of ffmpeg per image.
The idea in my example code is that this issue replicates for repeated library use because of global state pollution that will be hard (impossible) to replicate with repeated process invocation.

**Comment by hassount** [comment]
@itaibenari thank you for the additional details. I am going to open this up for help while we finish what we have at hand Someone from the community might be able to address this. As soon as we are at a context switch point, we'll make sure to look into this.

@1480c1 can you please queue this issue after we finish are done with #1531 ?

**Comment by 1480c1** [comment]
Currently trying to look into this and I notice a few issues, whenever I run it, it seems to print out
```none
Error: ../Source/Lib/Encoder/Codec/aom_dsp_rtcd.c:379: Pointer "svt_compute_interm_var_four8x8" is set before!
Error: ../Source/Lib/Encoder/Codec/aom_dsp_rtcd.c:380: Pointer "sad_16b_kernel" is set before!
Error: ../Source/Lib/Encoder/Codec/aom_dsp_rtcd.c:381: Pointer "svt_av1_compute_cross_correlation" is set before!
Error: ../Source/Lib/Encoder/Codec/aom_dsp_rtcd.c:382: Pointer "svt_av1_k_means_dim1" is set before!
Error: ../Source/Lib/Encoder/Codec/aom_dsp_rtcd.c:383: Pointer "svt_av1_k_means_dim2" is set before!
Error: ../Source/Lib/Encoder/Codec/aom_dsp_rtcd.c:384: Pointer "svt_av1_calc_indices_dim1" is set before!
Error: ../Source/Lib/Encoder/Codec/aom_dsp_rtcd.c:385: Pointer "svt_av1_calc_indices_dim2" is set before!
Error: ../Source/Lib/Encoder/Codec/aom_dsp_rtcd.c:386: Pointer "variance_highbd" is set before!
Error: ../Source/Lib/Encoder/Codec/aom_dsp_rtcd.c:387: Pointer "svt_av1_haar_ac_sad_8x8_uint8_input" is set before!
...
```
which I assume is because of the changes done recently

**Comment by itaibenari** [comment]
@hassount can I help with this issue somehow?

**Comment by 1480c1** [comment]
@itaibenari, can you try reproducing the issue again? I am trying to, but even after ~100 iterations, it is not erroring out

**Comment by itaibenari** [comment]
@1480c1 this does not reproduce in 0.8.6. I tested 0.8.5 (to make sure I was not misleading) and it did reproduce. you can close.
