### ISSUE TITLE
Custom prediction structure not working

### ISSUE THREAD

**Issue by kedartatwawadi** [AOMediaCodec/SVT-AV1#1567]
**Command:**  `SvtAv1EncApp -i input.y4m  --keyint 16 --hierarchical-levels 3  --pred-struct-file Config/PredStruct_level3.cfg  -b output.ivf`

**Error Message**: (Error: `Encoding          Error: can't find ref frame in dpb list0`) 

**Log**:
```
SVT [version]:  SVT-AV1 Encoder Lib v0.8.5-71-g2936d57
SVT [build]  :  GCC 5.4.0 20160609       64 bit
LIB Build date: Nov  9 2020 10:41:02
-------------------------------------------
Number of logical cores available: 8
Number of PPCS 46
[asm level on system : up to avx2]
[asm level selected : up to avx2]
------------------------------------------- 
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: Preset                                                    : 8 
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720 
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 30 / 1 / 17 / 2
SVT [config]: HierarchicalLevels  / PredStructure                               : 3 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 16 / 0 
------------------------------------------- 
Encoding          Error: can't find ref frame in dpb list0
```

The same command with July 1, 2020 build works: 
```
-------------------------------------------
SVT [version]:  SVT-AV1 Encoder Lib v0.8.4
SVT [build]  :  GCC 5.4.0 20160609       64 bit
LIB Build date: Jul  1 2020 12:33:37
-------------------------------------------
```

**Comment by Somdyuti2** [comment]
I am encountering the same error with all prediction structures from levels 3 through 5.  There might have been some recent changes that broke the manual prediction structure.  Please let us know, thanks.

**Comment by hassount** [comment]
@paulsgh can we track this ? 
@1480c1 we might need to add a ci to run a simple encode using all cfg files so that this does not break anymore.

**Comment by kedartatwawadi** [comment]
Happy to help out with fixing this! @hassount @paulsgh

**Comment by hassount** [comment]
> Happy to help out with fixing this! @hassount @paulsgh

Great, thank you, any help is much appreciated as we have a lot on our plate :)

**Comment by Somdyuti2** [comment]
Hi, any updates or an estimated time frame to fix this bug? @hassount , @paulsgh

**Comment by hassount** [comment]
@Somdyuti2 my understanding is that @kedartatwawadi was gonna take a stab at it.

**Comment by kedartatwawadi** [comment]
@hassount Yes, I am taking a look at it. Apologies for the delay! I will get back with questions/updates in a day or two

**Comment by kedartatwawadi** [comment]
@hassount I think I was able to fix the issue: https://github.com/AOMediaCodec/SVT-AV1/pull/1612
The issue seems to have crept in the commit id: a0f233f6ba5d173fc8e258ded045fb0d75074747 . Can't say I completely understand the code here, but this seemed to be the difference between the commit where the issue first surfaced. 

I verified that the encoding is successful for `Config/PredStruct_level3.cfg` and generates correct prediction structure using the AOM Analyzer https://pengbins.github.io/aomanalyzer.io/. 

I believe it would be useful to add a test to catch issues in the future. Any suggestions on how can I proceed about the same?

**Comment by hassount** [comment]
> @hassount I think I was able to fix the issue: #1612
> The issue seems to have crept in the commit id: [a0f233f](https://github.com/AOMediaCodec/SVT-AV1/commit/a0f233f6ba5d173fc8e258ded045fb0d75074747) . Can't say I completely understand the code here, but this seemed to be the difference between the commit where the issue first surfaced.
> 
> I verified that the encoding is successful for `Config/PredStruct_level3.cfg` and generates correct prediction structure using the AOM Analyzer https://pengbins.github.io/aomanalyzer.io/.
> 
> I believe it would be useful to add a test to catch issues in the future. Any suggestions on how can I proceed about the same?

@kedartatwawadi thank you very much, I agree, a test would be good to have to make sure this does not break anymore.

**Comment by paulsgh** [comment]
Using PR #1612 (d63e804) on Linux, I tested `SvtAv1EncApp -i input.y4m --keyint 16 --hierarchical-levels 3 --pred-struct-file Config/PredStruct_level3.cfg -b output.ivf` using prediction structures levels 3 through 5, and was unable to reproduce the error.

**Comment by kedartatwawadi** [comment]
@paulsgh Sorry I didn't understand what you said. Is the error not present after https://github.com/AOMediaCodec/SVT-AV1/pull/1612 ?

**Comment by paulsgh** [comment]
@kedartatwawadi no problem.
Yes what you said is correct. The error was not present when I tested your command using #1612.
