### ISSUE TITLE
Support & test Arm64 builds on macOS and Windows

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/SVT-AV1#1569]
Here's a tracking issue for Arm64 support on both macOS and Windows. The opening of this issue corresponds with the release of Xcode 12.2 and Visual Studio 16.8.

**macOS**
 - [x] Migrate to Xcode 12.2 (switched to by default with https://github.com/actions/virtual-environments/pull/2177)
 - [ ] Compile universal binaries supporting Apple Silicon (silly attempt #1617)
 - [ ] Add testing on Apple Silicon systems
 - [ ] Deploy universal binaries to GitHub on release

**Windows**
 - [ ] Migrate to Visual Studio 16.8 (currently waiting on https://github.com/actions/virtual-environments/issues/2022)
 - [ ] Compile Arm64 builds
 - [ ] Add testing on Arm64 builds
 - [ ] Deploy Arm64 executables to GitHub on release

 @1480c1 and others, please deliver input on this!

**Comment by spawlows** [comment]
Why are we removing Sanitizer from CI?

**Comment by hassount** [comment]
> Why are we removing Sanitizer from CI?

We’re not.
