### ISSUE TITLE
High Memory Usage and R2R in VBR Mode

### ISSUE THREAD

**Issue by paulsgh** [AOMediaCodec/SVT-AV1#1574]
## Description:
There is high memory usage in VBR mode, seen when running either nightly stability or PR performance tests on PR #1559, causing the tests to become unstable. Several encoding logs show the commands were terminated by signal 9.

After implementing a quick-fix to stabilize the tests (see: Initial Debugging), R2R is found in 10bit VBR.

**Encoder:** svt
**Revision:** [s03_pr1@af0791d](https://github.com/chkngit/SVT-AV1/commit/af0791d67ec427573defc34f3a78e57ed8e46f20)

#### Observed in Nightly Stability
- **8bit VBR:** unable to complete as the logs became so large that the machine ran out of space
- **10bit VBR:** tests finished with nonsensical results in the R2R log

#### Observed in PR Performance Tests
- **8bit VBR:** unable to complete as the logs became so large that the machine ran out of space
- **10bit VBR:** finished with several errors

## Sample Command Lines:
**8bit:**
`./SvtAv1EncApp -enc-mode 8 --passes 2 --irefresh-type 2 -w 1920 -h 1080 -bit-depth 8 -fps-num 60000 -fps-denom 1000 -n 60 --rc 1 --tbr 2000 -intra-period 119 -enable-tpl-la 1 -lp 1 -i /home/ubuntu/stream/8bit/Netflix_PierSeaside_1920x1080_60fps_8bit_420_60f.yuv --stats bitstreams/svt_2p_M8_Netflix_PierSeaside_1920x1080_60fps_8bit_420_60f_RC_TBR_2000Kbps.stat -b bitstreams/svt_2p_M8_Netflix_PierSeaside_1920x1080_60fps_8bit_420_60f_RC_TBR_2000Kbps.bin`

**10bit:**
`./SvtAv1EncApp -enc-mode 8 --passes 2 --irefresh-type 2 -w 1920 -h 1080 -bit-depth 10 -fps-num 60000 -fps-denom 1000 -n 60 --rc 1 --tbr 1000 -intra-period 119 -enable-tpl-la 1 -lp 1 -i /home/ubuntu/stream/10bit/Netflix_Aerial_1920x1080_60fps_8bit_420_60f_10bit.yuv --stats bitstreams/svt_2p_M8_Netflix_Aerial_1920x1080_60fps_8bit_420_60f_10bit_RC_TBR_1000Kbps.stat -b bitstreams/svt_2p_M8_Netflix_Aerial_1920x1080_60fps_8bit_420_60f_10bit_RC_TBR_1000Kbps.bin`

## Initial Debugging:
- workaround was to decrease the number of parallel jobs to 30, with this:
  - there are no longer any errors
  - there is R2R found in 10bit VBR
- the memory usage is still very high though, as seen in [the results](https://github.com/AOMediaCodec/SVT-AV1/pull/1559#issuecomment-726316843) of the performance tests on PR #1559

**Comment by hassount** [comment]
@anaghdin @kelvinhu325

**Comment by anaghdin** [comment]
@paulsgh Thanks for testing and detailed description. To clarify, were both issues (memory and R2R in 10 bit) introduced in the PR?

**Comment by paulsgh** [comment]
@anaghdin No problem. Yes, both issues (memory and R2R in 10bit) were introduced in the PR.

**Comment by hassount** [comment]
@paulsgh can we retest this to make sure it's good now ?

**Comment by paulsgh** [comment]
@hassount I have confirmed this issue has been fixed by running performance and stability VBR tests using the regular number of parallel jobs, on the latest master.
