### ISSUE TITLE
CI: Fix macOS unit tests

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/SVT-AV1#1577]
It seems that the [unit tests on macOS](https://github.com/AOMediaCodec/SVT-AV1/blob/master/.github/workflows/macos.yml#L135) are [broken on the master branch](https://github.com/AOMediaCodec/SVT-AV1/actions?query=workflow%3AmacOS+branch%3Amaster). The last working build was on [November 6th](https://github.com/AOMediaCodec/SVT-AV1/runs/1361594157), and the first failing run was on [November 11th](https://github.com/AOMediaCodec/SVT-AV1/runs/1383643982). That was after merging #1559, but a change in the CI build environment could also be the root of the problem.

Since GitHub Actions only displays a _This check failed_ message and no log or anything, I suspect that it is an environment thing.

Note that this test is completed on a self-hosted runner. Maybe someone could check the status of this machine? (maybe someone tripped over a wire)

This guide could also help: [Monitoring and troubleshooting self-hosted runners](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/monitoring-and-troubleshooting-self-hosted-runners#checking-the-status-of-a-self-hosted-runner)

**Comment by hassount** [comment]
@EwoutH thank you for the issue, we are looking into this, and yes it seems that the machines are down and are working with the hosting team on getting them back up

**Comment by hassount** [comment]
This is now done, runner issue addressed and hidden failures addressed one by one: #1592 #1599 #1601 and #1587
