### ISSUE TITLE
Passing through color_range properly with ffmpeg from decoded frame to SVT-AV1 crashes the encoder

### ISSUE THREAD

**Issue by BlueSwordM** [AOMediaCodec/SVT-AV1#1580]
**What steps will reproduce the problem?**
1. Compile ffmpeg git from October 29th onwards.
2. Encode video stream to y4m/pipe the stream from ffmpeg to SVT-AV1 with any encoding settings whatsoever.
3. Encode the video stream with SVT-AV1.

**What is the expected output?**
Encoder works fine.

What do you see instead?
Error parsing header; not a YUV2MPEG2 file?
Fatal: Unsupported Y4M stream.

**What version / commit were you testing with? (git describe can produce this
info if building from source). On what operating system?**

SVT-AV1 Encoder Lib v0.8.5-71-g2936d575

Ubuntu 20.04
Windows 10 2004

**Please provide any additional information below.**

The offending ffmpeg bug report can be seen here, along with some tips to probably fix it:
https://trac.ffmpeg.org/ticket/8958#comment:6

Commit that affected some AV1 encoders like aomenc and SVT-AV1(rav1e seems to be fine in testing since it can work with the color information passed already): https://git.videolan.org/gitweb.cgi/ffmpeg.git/?a=commit;h=7369595c556516b90bf3acdf85043dc11add7d89

Can be temporarily fixed by setting the ffmpeg option -color_range 0, which does not pass any color information(limited/full?) to the encoder, making it work fine.

**Comment by hassount** [comment]
@BlueSwordM thank you for the detailed description. @1480c1 can you please queue this issue to look into and we can discuss how to best proceed
