### ISSUE TITLE
How to pass QP value when use ffmpeg command with libsvt_av1 ?

### ISSUE THREAD

**Issue by lien006** [AOMediaCodec/SVT-AV1#1583]
when i use follow command:
ffmpeg -i test_video.ts -c:v libsvt_av1 -acodec copy  -q 30 -preset 8  -tile-columns 2 -tile-rows 2 -row-mt 1 -threads 8 -s 840x480 output_840x480_q30.mp4

the encoder output parameters are:
-------------------------------------------
SVT [version]:	SVT-AV1 Encoder Lib v0.8.4
SVT [build]  :	GCC 4.8.5 20150623 (Red Hat 4.8.5-39)	 64 bit
LIB Build date: Jul  1 2020 18:11:49
-------------------------------------------
Number of logical cores available: 4
Number of PPCS 72
[asm level on system : up to avx512]
[asm level selected : up to avx2]
------------------------------------------- 
SVT [config]: Main Profile	Tier (auto)	Level (auto)	
SVT [config]: EncoderMode 							: 8 
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat	: 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight					: 840 / 480 
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType 	: 25 / 1 / 33 / 2
SVT [config]: HierarchicalLevels  / PredStructure		: 4 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange			: CQP / 50 / 33 / 0 

The QP value is still default 50, how to set QP ?

**Comment by hassount** [comment]
can you try -qp 30 instead of -q 30 ?

**Comment by hassount** [comment]
closing this, please re-open if the issue persists.
