### ISSUE TITLE
input 720P encoder hang up in version of 0.8.5

### ISSUE THREAD

**Issue by xudongxu135** [AOMediaCodec/SVT-AV1#1584]
This problem seems to be no the same with https://github.com/AOMediaCodec/SVT-AV1/issues/1499.
cmd below:
ffmpeg  -i test1.mp4  -vcodec libsvtav1  -vb 2000k test2.mp4
LOG below
########################################
SVT [version]:  SVT-AV1 Encoder Lib v0.8.5
Number of logical cores available: 48
Number of PPCS 94
[asm level on system : up to avx2]
[asm level selected : up to avx2]
------------------------------------------- 
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: Preset                                                    : 8 
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1280 / 720 
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType     : 20 / 1 / 17 / 2
SVT [config]: HierarchicalLevels  / PredStructure                               : 4 / 2
SVT [config]: RCMode / TargetBitrate (kbps)/ LookaheadDistance / SceneChange            : Constraint VBR / 2000 / 16 / 0 
#######################################################
I use 3 sequences encoded with threee different encoders for input,that is, test1.mp4=h264.mp4 || test1.mp4=h265.mp4 || test1.mp4=av1.mp4,  problems are the same: **when encode some frames, libsvtav1 hang up**
when I try to change preset, gop size, HierarchicalLevels  ,LookaheadDistance, Fps_Numerator,problem still occur.
I use gdb to debug, bt shows info below , it seems a deadlock happens in libsvtav1 :

 in do_futex_wait.constprop.1 () 
 in __new_sem_wait_slow.constprop.0 () 
in sem_wait@@GLIBC_2.2.5 ()
in eb_block_on_semaphore () 
in eb_get_empty_object () 
 in svt_av1_enc_send_picture () 
#######################################
some times will show info below:
in do_futex_wait.constprop.1 () 
in __new_sem_wait_slow.constprop.0 () 
 in sem_wait@@GLIBC_2.2.5 () 
 in eb_block_on_semaphore ()
 in eb_get_full_object () 
n svt_av1_enc_get_packet ()

########################################
NOTE:when I use 1920:1080 sequeces for input, then libsvtav1 works fine, even thoug I add -vf scale=1280:720:
ffmpeg  -i test1.mp4  -vcodec libsvtav1 -vf scale=1280:720  -vb 2000k test2.mp4
Can anyone lookinto this problem?

**Comment by xudongxu135** [comment]
update:when use version of 0.8.0, it works fine.

**Comment by xudongxu135** [comment]
I have checked this problem can be reproduced using the latest version of master.

**Comment by xudongxu135** [comment]
Maybe it is depend on the special stream files and threads. My linux machine has 48 cores @kelvinhu325

**Comment by kelvinhu325** [comment]
> Maybe it is depend on the special stream files and threads. My linux machine has 48 cores @kelvinhu325

Thanks, my machine has 112 cores, I tried to run 3000 frames with -ss 0, it gets segment fault with error log on EbInitialRateControlProcess.c:1516 and queue_entry_index_temp=2048 makes array access over range, looks not the same issue as yours.

**Comment by hassount** [comment]
@anaghdin FYI

**Comment by kelvinhu325** [comment]
> @anaghdin FYI

Quick debugged it, and found the below change can fix this issue, it should use clamped index to avoid arry access over range.
@@ -1512,7 +1512,7 @@ void *initial_rate_control_kernel(void *input_ptr) {
                         PictureParentControlSet* pcs =
                             (PictureParentControlSet*)(encode_context_ptr
                                                            ->initial_rate_control_reorder_queue
-                                                               [queue_entry_index_temp]
+                                                               [queue_entry_index_temp2]
                                                                ->parent_pcs_wrapper_ptr)->object_ptr;

**Comment by anaghdin** [comment]
Thanks Kelvin, yes makes sense. queue_entry_index_temp2 should be used.

**Comment by hassount** [comment]
@xudongxu135 can you please check if the latest master addressed your issue ?

**Comment by xudongxu135** [comment]
sorry for late reply. I will check asap
