### ISSUE TITLE
add the support to specify per layer qindex offset and chroma qindex offsets

### ISSUE THREAD

**Issue by PDX-Runner** [AOMediaCodec/SVT-AV1#1619]
current AVT AV1 does not allow user to specify the qindex offsets and chroma qindex offset for different temporal layers.

**Comment by PDX-Runner** [comment]
supported by pull-request https://github.com/AOMediaCodec/SVT-AV1/pull/1618

**Comment by paulsgh** [comment]
Verified PR #1618 successfully supports this patch; tested on Linux.
