### ISSUE TITLE
master e502bf698640e33daff59a436d08b7433ca79907 crashes with Division By Zero exception on VBR when lad > intra period

### ISSUE THREAD

**Issue by palexander-14** [AOMediaCodec/SVT-AV1#1621]
Crash happens most likely on all platforms (checked on windows and linux) with any source file and resolution. The condition for crash is lookahead distance is more than intra period (GOP) length.

Command line to reproduce:
`SvtAv1EncApp -i input.yuv -w 1280 -h 720 --output out.ivf --rc 1 --tbr 2500 --fps 24 --preset 8 --keyint 47 --lookahead 48`

Crash happens at https://github.com/AOMediaCodec/SVT-AV1/blob/e502bf698640e33daff59a436d08b7433ca79907/Source/Lib/Encoder/Codec/EbRateControlProcess.c#L1686
A quick investigation shows that `hl_rate_control_histogram_ptr_temp` points to an uninitialized/invalid data and `hl_rate_control_histogram_ptr_temp->full_sb_count` is 0.

**Comment by hassount** [comment]
closing this for #1622
