### ISSUE TITLE
master crashes with Division By Zero exception on VBR when lad > intra period

### ISSUE THREAD

**Issue by palexander-14** [AOMediaCodec/SVT-AV1#1622]
Crash happens most likely on all platforms (checked on windows and linux) with any source file and resolution. The condition for crash is lookahead distance is more than intra period (GOP) length.

Command line to reproduce:
`SvtAv1EncApp -i input.yuv -w 1280 -h 720 --output out.ivf --rc 1 --tbr 2500 --fps 24 --preset 8 --keyint 47 --lookahead 48`

Crash happens at https://github.com/AOMediaCodec/SVT-AV1/blob/e502bf698640e33daff59a436d08b7433ca79907/Source/Lib/Encoder/Codec/EbRateControlProcess.c#L1686
A quick investigation shows that `hl_rate_control_histogram_ptr_temp` points to an uninitialized/invalid data and `hl_rate_control_histogram_ptr_temp->full_sb_count` is 0.

**Comment by palexander-14** [comment]
Some additional information.

Crash happens on the very first picture with command line like this:
`SvtAv1EncApp -i input.yuv -w 1280 -h 720 --output out.ivf --rc 1 --tbr 2500 --fps 24 --preset 8 --keyint 47 --lookahead 48`

You can see the crash on the following screenshot:
![Crash](https://user-images.githubusercontent.com/63088100/101731568-65d4bb80-3aee-11eb-983d-fa9e3a0cfde6.PNG)

Here you can see the function in which the crash is happened, in the watch window you can see that
`hl_rate_control_histogram_ptr_temp->full_sb_count` is 0
![Debug-0-Inside_predict_bits](https://user-images.githubusercontent.com/63088100/101731575-679e7f00-3aee-11eb-9960-8c34d326ad33.PNG)

On the following screenshot
![Debug-1-Inside_RC](https://user-images.githubusercontent.com/63088100/101731576-679e7f00-3aee-11eb-90ce-194a77787215.PNG)
Last two entries of `encode_context_ptr->hl_rate_control_historgram_queue` is showed.
47th initialized with correct data, while 48th is not.


A short debugging showed that the condition located at
https://github.com/AOMediaCodec/SVT-AV1/blob/7beb2754eeb4b33d289901e8af90e43c4db9028b/Source/Lib/Encoder/Codec/EbInitialRateControlProcess.c#L480-L481
prevents initial_rate_control_kernel from filling initial_rate_control_reorder_queue array beyond GOP boundary. When this condition is disabled, the encoder stops crashing.

**Comment by paulsgh** [comment]
I'm unable to reproduce the issue using PR #1632; tested on both Linux and Windows.
