### ISSUE TITLE
Lossless support?

### ISSUE THREAD

**Issue by eclipseo** [AOMediaCodec/SVT-AV1#1636]
Is any lossless support planned in SVT-AV1? This would be nice to have to use with libavif.

Thanks.

**Comment by lextra2** [comment]
If you want lossless why not use libx264? Not even FFV1 can beat it in efficiency. And I highly doubt av1 would either.

**Comment by hassount** [comment]
I don't see lossless support on the roadmap, that said, contributions are most welcome in this area.
