### ISSUE TITLE
is what prepare output buffer better?

### ISSUE THREAD

**Issue by changtj** [AOMediaCodec/SVT-AV1#1640]
enc app:

 EbErrorType stream_status = svt_av1_enc_get_packet(
            component_handle, &header_ptr, 0);
// Release the output buffer
            svt_av1_enc_release_out_buffer(&header_ptr);

if we prepare output buffer, then it should reduce copy times.

**Comment by hassount** [comment]
can you please elaborate further on what is needed here ?

**Comment by changtj** [comment]
function use( ){  }

function copydo( buff ){ 

char * buffa = buff[nIndex++];
/**
before use ,must copy
**/
 memcpy(  buffa, buff );

new thread( [](){
  use();
})
  
}

EbErrorType stream_status = svt_av1_enc_get_packet(
component_handle, &header_ptr, 0);
// Release the output buffer
copydo( header_ptr )
svt_av1_enc_release_out_buffer(&header_ptr);

//////////////////////////////////////////////////////////////////////////////////////////////////////////////
if prepare buffer:


function use( ){  }

function copydo( buff ){ 

//char * buffa = buff[nIndex++];
/**
 this case , not need copy
**/
// memcpy(  buffa, buff );

new thread( []( buff ){
  use( buff );
})
  
}

EbErrorType stream_status = svt_av1_enc_get_packet(
component_handle, &header_ptr, 0);
// Release the output buffer
copydo( header_ptr )
svt_av1_enc_release_out_buffer(&header_ptr);

**Comment by changtj** [comment]
> can you please elaborate further on what is needed here ?

for example as follow.
////////////////////////////////////////////////////////
now case, must copy;

function use( ){ }

function copydo( buff ){

char * buffa = buff[nIndex++];
/**
before use ,must copy
**/
memcpy( buffa, buff );

new thread( {
use();
})

}

EbErrorType stream_status = svt_av1_enc_get_packet(
component_handle, &header_ptr, 0);
// Release the output buffer
copydo( header_ptr )
svt_av1_enc_release_out_buffer(&header_ptr);

//////////////////////////////////////////////////////////////////////////////////////////////////////////////
if prepare buffer:

function use( ){ }

function copydo( buff ){

//char * buffa = buff[nIndex++];
/**
this case , not need copy
**/
// memcpy( buffa, buff );

new thread( {
use( buffa );
})

}

EbErrorType stream_status = svt_av1_enc_get_packet(
component_handle, &header_ptr, 0);
// Release the output buffer
copydo( header_ptr )
svt_av1_enc_release_out_buffer(&header_ptr);

**Comment by hassount** [comment]
@changtj 
back to this issue, the output buffer would need to be recycled and such is why the copy is needed. It might be that I am missing your point here. Please feel free to submit a pull request with whatever changes you see fit and we can take it from there.
