### ISSUE TITLE
SVT crashes at 147 frames when using IP 150, preset 4

### ISSUE THREAD

**Issue by bzhutencent** [AOMediaCodec/SVT-AV1#1644]
SVT crashes at 147 frames while using the following command line

Command line:
SvtAv1EncApp -i PartyScene_832x480_50.yuv -b Bin_preset4enable-tpl-la1_T2RA_VVCC_C3_R1_qp20_s0_f300_t1.bin --width 832 --height 480 --rc 0  --qp 20 --min-qp 1 --max-qp 63  --frames 300 --keyint 150 --fps-num 50 --fps-denom 1  --input-depth 8 --irefresh-type 1  --lp 1 --preset 4 --enable-tpl-la 1

**Comment by tszumski** [comment]
@ttrigui, @hassount 

This crash is introduced in:
    Commit aa0f6823 In-loop ME and TPL (#1559)
    Feature #define **FEATURE_PA_ME**

**Comment by tszumski** [comment]
For faster debugging CMD can be reduced to:
```
-i PartyScene_832x480_50.yuv --irefresh-type 1 -b out.bin -w 832 -h 480 --input-depth 8 --preset 8 --enable-tpl-la 1 -n 35 --keyint 17
```
