### ISSUE TITLE
[Question] Regarding the subpel refinement code for motion estimation

### ISSUE THREAD

**Issue by Somdyuti2** [AOMediaCodec/SVT-AV1#1656]
Hi, could you please point me to the section of the code that performs the open loop subpel refinement after the integer motion search as described in the appendix [SVT-AV1/Docs/Appendix-Subpel-Interpolation-Open-Loop-ME.md](https://github.com/AOMediaCodec/SVT-AV1/blob/master/Docs/Appendix-Subpel-Interpolation-Open-Loop-ME.md) as well as  to the data structure that holds the subpel precision MVs after the refinements? After inspecting the code, it seemed that the subpel refinement is only being used while performing motion estimation for temporal filtering in  `EbTemporalFiltering.c ` ( `tf_32x32_sub_pel_search(...)` and  `tf_16x16_sub_pel_search(...)` ), but no such refinement steps are there after the integer search (`motion_estimate_sb()`) in  `EbMotionEstimationProcess.c`.  Further, at all presets, it seems that the flag `pcs_ptr->frm_hdr.allow_high_precision_mv` is disabled for every picture within the motion estimation kernel, and a seemingly related function called `su_pel_enable(...)` in `EbMotionEstimation.c ` is also left unused.  I have looked at other parts of the encoder code too, but could not locate the related open loop refinement step. 

Also, according to [Appendix-Compliant-Subpel-Interpolation-Filter-Search.md](https://github.com/AOMediaCodec/SVT-AV1/blob/master/Docs/Appendix-Compliant-Subpel-Interpolation-Filter-Search.md), MVs can be specified  up to eighth-pel accuracy, but according to [Appendix-Subpel-Interpolation-Open-Loop-ME.md](https://github.com/AOMediaCodec/SVT-AV1/blob/master/Docs/Appendix-Subpel-Interpolation-Open-Loop-ME.md)  the open loop motion estimation provides motion vectors up to quarter-pel precision. Does that mean that the final eighth-pel refinement step takes place in closed loop in conjunction with the mode decision and rate control processes or merely that the eighth-pel precision motion vector estimation is not implemented yet in this encoder? 

Clarifications on the couple of points above would be really helpful. Thanks.

**Comment by hassount** [comment]
@Somdyuti2 thank you for the question and I apologize for the late response, I do see that there's definitely a need to update the documentation, so we'll need to do a round on that soon. In the meantime, @fouedb can you please help answering this question ?

**Comment by fouedb** [comment]
1.	Temporal filtering: Interpolation search up to eighth-pel accuracy is performed in the functions tf_32x32_sub_pel_search and tf_16x16_sub_pel_search using eight-tap regular filters.  
2.	Open loop ME: No interpolation search.
3.	ME First Pass: No interpolation search. 
4.	MD: Interpolation search is performed using the function md_subpel_search. The latter is called in two functions in MD:  
        - read_refine_me_mvs: The interpolation search settings for this function are given in  md_subpel_me_controls
        - pme_search: The interpolation search settings for this function are given in  md_subpel_pme_controls

**Comment by Somdyuti2** [comment]
Thanks a lot for the clarifications.
