### ISSUE TITLE
what is the configuration in real-time use?

### ISSUE THREAD

**Issue by changtj** [AOMediaCodec/SVT-AV1#1659]
what is the configuration in real-time use?

important, encoder as soon as encode out the frame when input one source frame data.

**Comment by changtj** [comment]
> This seems to be a duplicate of #1658
> 
> @changtj a 1-frame real-time latency is currently not supported, the encoder does support real-time performance with a few sec latency with a 5-layer hierarchical structure and some lookahead window based on features enabled such would require the buffering of several frames. right now, the lag in frames should be 24 frames and not 37 in CRF mode (--rc 0) and such will soon be applicable to VBR.

thanks, i try aom av1,  the lag can be set to 0.

**Comment by hassount** [comment]
> > This seems to be a duplicate of #1658
> > @changtj a 1-frame real-time latency is currently not supported, the encoder does support real-time performance with a few sec latency with a 5-layer hierarchical structure and some lookahead window based on features enabled such would require the buffering of several frames. right now, the lag in frames should be 24 frames and not 37 in CRF mode (--rc 0) and such will soon be applicable to VBR.
> 
> thanks, i try aom av1, the lag can be set to 0.

understood, it's a use case that encoders may / may not chose to implement depending on the target application.
