### ISSUE TITLE
Produced files are incompatible with VLC fast seeking, even with IntraRefreshType = 2

### ISSUE THREAD

**Issue by gcp** [AOMediaCodec/SVT-AV1#1667]
Videos encoded with SVT-AV1 0.8.6-29-gb6e11146, using Gop Size = 300 and IntraRefreshType = 2.

VLC is unable to seek in these files if fast seeking is enabled (which seems to be the default on Android). Because playback of a previously viewed file involves a seek, they effectively can't be played back more than once.

I've seen a lot of problem reports with seeking behavior, but they're all due to Open GOP. As noted above, that's not the problem here and I'm using full IDR.

Files produced by libaom-av1 do not exhibit this behavior and play back correctly - which is why I'm reporting it here and not on the VLC bugtracker.

**Comment by gcp** [comment]
Using current ffmpeg (ffmpeg version 2021-01-01-git-63505fc60a) with this command line:
ffmpeg -i blah.mkv -c:v libsvtav1 -preset 5 -qp 54 -g 300 -threads 12 -c:a libopus -b:a 80k "blah.webm"

**Comment by 1480c1** [comment]
@gcp can you potentially share your exact build of ffmpeg and also information such as what OS you encoded on and what OS(es) you played the video on along with video size? Is it only on Android?

Have you tested the latest master branch? If you are on windows, a build can be found at https://github.com/AOMediaCodec/SVT-AV1/suites/1808568177/artifacts/34738218 or at https://gitlab.com/1480c1/SVT-AV1/-/jobs/956032897/artifacts/download, however, they lack libopus so you would need to change your line to `-c:a opus -strict -2`

When you mean
> VLC is unable to seek in these files if fast seeking is enabled

do you mean VLC completely refuses to play if you seek or is there a delay?

Also, can you clarify what effects does fast seek have or how to tell if it's actually in effect? I see the option in the settings menu and have it on, but I am unable to see any difference in playback from an encoded file with it on or off (encoded on windows `v0.8.6-55-g9b67af03-dirty` and played on windows and played on android vlc)

**Comment by gcp** [comment]
IIRC it was a "full" build from here, date and git tag are above: https://www.gyan.dev/ffmpeg/builds/packages/

Playback was tested on Linux and Android, the behavior was similar. But at least the VLC 3.0.8 (a bit older) on my Linux system did not default to fast seeking, so the problem there wasn't visible until I explicitly enabled it. On Android it is defaulted on so it's there that I noticed it.

VLC is completely unable to seek with fast seeking. I should be specific: it seeks the audio track, but the video track stays black. If I disable fast seeking, it seeks, but there's a visible delay. Neither of this happens with libaom-av1 encoded files. I don't know how to tell whether fast seeking is in effect aside from the behavior above.

I'll test the build you linked.

**Comment by hassount** [comment]
@gcp 
would you be able to  update a sample bitstream that shows the issue ?

**Comment by gcp** [comment]
I can try to find some non-copyrighted material and see if the issue doesn't depend on the source maybe.

**Comment by gcp** [comment]
The build you linked didn't produce the issue. Looking at the repo here, there don't seem to be relevant changes to the SVT-AV1 repo. Does this mean this potentially regressed in ffmpeg git?

**Comment by 1480c1** [comment]
Although I doubt it since I don't remember any particular commit since January that might have affected svt-av1 specifically in FFmpeg, but I can't rule that out.

**Comment by gcp** [comment]
I tested with a free Blender clip, but that is seekable. I do notice it only seeks to scene changes (with fast seeking enabled).

So that's a peculiar thing about my source material: It has no scene changes in it in whatsoever.

The -g 300 is supposed to limit the max GOP to 300 frames right? Is it possible this is/was broken?

**Comment by hassount** [comment]
The notion of max and min keyframe is combined in SVT-AV1. So it means that -g 300, will force a key frame every 300 frames nothing in between. Which might be why you wouldn’t be able to seek frequently

**Comment by gcp** [comment]
Yes, this is my understanding. But the behavior I'm seeing from the broken combo seems to imply that despite the above output it's being ignored and only putting them at scene changes. I'll try encoding the Blender clip with a GOP=30 and then see if I can seek with second granularity. If I can't, that means I have a redistributable clip with the issue.

**Comment by gcp** [comment]
I think I have a repro that I can make public:
https://sjeng.org/ftp/work/TestSeek-Spring-G30.webm

This was encoded with the ffmpeg linked above, which is the Windows build the official site links to:
``ffmpeg -i spring-vp9-vorbis.webm -c:v libsvtav1 -preset 5 -qp 54 -g 25 -strict -2 -c:a opus -b:a 80k -threads 12 TestSeek-Spring-G30.webm``

If I try to seek in this with VLC on Android, I should be able to get to ~1s with fast seeking. But I have the impression it will only seek to scene changes.

**Comment by 1480c1** [comment]
Usually, when someone provides a repro, they provide a link or way to get the original sample rather than the output only, I am assuming the original is https://tools.woolyss.com/html5-audio-video-tester/?u=woolyss.com/f/spring-vp9-vorbis.webm

Playing back both your sample and encoding my own sample using the latest git ffmpeg from gyan and your command line, I am able to seek in 1 s intervals with fast seek enabled and both video and audio played fine on windows 10 (3.0.11), linux (manjaro, 3.0.11.1), and android (3.3.2) (I tried playing on an iPhone 11 Pro, but it seems vlc on iPhone does not have av1 support) and even spam seeking from beginning to end to middle at random worked fine as well.

I do notice that when encoding with opus, it mentioned `Queue input is backward in time` and `Non-monotonous DTS in output stream 0:1; previous: 1979, current: 1976; changing to 1979. This may result in incorrect timestamps in the output file.`, but it doesn't seem like it affected the output.

Just to make sure, can you check what versions of vlc you have installed?

**Comment by BlueSwordM** [comment]
I have tried to reproduce this issue with libsvtav1 inside of ffmpeg and the standalone binary and I can't reproduce the issue of the OP on multiple devices (VLC latest nightly on Android, VLC 3.0.11, custom mpv built on January 5th with latest ffmpeg at the time)
The video encoded in question comes from the Xiph.org Derf collection, being the Witcher 3 video:
https://media.xiph.org/video/derf/

**Comment by gcp** [comment]
>they provide a link or way to get the original sample rather than the output only,

As already stated, it is copyrighted material that I have no license to redistribute for.

>Just to make sure, can you check what versions of vlc you have installed?

VLC for Android Revision 7ec77872d VLC: f83f3a317 (2021-01-11)

I'll switch this back to release (from beta) and see if that changes anything.

**Comment by gcp** [comment]
I have steps to reproduce!

https://sjeng.org/ftp/work/chess.mkv

Encoded with the above ffmpeg and ``ffmpeg -i chess.mkv -c:v libsvtav1 -r 24 -preset 5 -qp 54 -g 300 -threads 12 -b:a 80k "SVTAV1-G300-F24.webm" produces: https://sjeng.org/ftp/work/SVTAV1-G300-F24.mkv

Play this file with VLC for Android. This works. Now seek a few times back and forth. The video will freeze.

The original file that produced this had a FPS of 23.976 (detected as 2995/125 by SVT-AV1). There may be some relation because the bug doesn't trigger with the original chess.mkv file which is 60 FPS.

**Comment by BlueSwordM** [comment]
I do not think this issue is related to SVT-AV1 specifically, since I only encounter the issue in VLC for Android, and not mpv-android or AOS-AVP.

All other players seem to work fine with this video sample.

**Comment by 1480c1** [comment]
For https://sjeng.org/ftp/work/SVTAV1-G300-F24.webm, I was able to reproduce vlc showing a black screen but audio being played on Linux, looking at the messages for errors, I see
```none
gl info: Initialized libplacebo v2.72.0 (API v72)
dav1d error: Decoder feed error -22!
main error: buffer deadlock prevented
main error: buffer deadlock prevented
```
same with windows, going to see if forcing aomdec works or not, and if not, going to try a beta version of vlc

**Comment by 1480c1** [comment]
forcing libaom produces
```none
main error: Timestamp conversion failed for 2757001: no reference clock
main error: Could not convert timestamp 0 for aom
main error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)
main error: Could not convert timestamp 257075273001 for aom
aom error: Failed to decode frame: Corrupt frame detected (Failed to decode tile data)
aom error: Failed to decode frame: Corrupt frame detected (Failed to decode tile data)
aom error: Failed to decode frame: Corrupt frame detected (Failed to decode tile data
```

**Comment by 1480c1** [comment]
using debug shows
```
main debug: Stream buffering done (1027 ms in 4 ms)
main debug: Received first picture
aom error: Failed to decode frame: Corrupt frame detected (Failed to decode tile data)
aom error: Failed to decode frame: Corrupt frame detected (Reference frame containing this frame's initial frame context is unavailable.)
(last line repeated multiple times)
```

**Comment by gcp** [comment]
It looks like I found a (single) libaom-av1 encoded file that has the same problem. So this might be a bug in ffmpeg muxing or the decoders that's just easier to hit with how SVT-AV1 encodes.

**Comment by hassount** [comment]
thank you guys, so in summary:
- this is reproducible with both libaom and svt-av1
- decoder issue shows up on both libaom and libdav1d
we're either looking at ffmpeg muxing or VLC ?

@jbkempf FYI

**Comment by gcp** [comment]
That seems most likely, unless SVT-AV1 and libaom have the exact same bug (not impossible either I guess...). The source clip I found that fails with libaom-av1 too, also fails with the git build of SVT-AV1 that you linked earlier. Unfortunately I don't have any free clip doing this. 

I've looked at the fails-with-both-encoders clip, and I did find something interesting. ffprobe claims it is 30 fps:

```
Input #0, matroska,webm, from '00.Introduction.mkv':
  Metadata:
    ENCODER         : Lavf58.45.100
  Duration: 00:08:00.24, start: 0.000000, bitrate: 1000 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(tv, unknown/bt709/unknown, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 30 fps, 30 tbr, 1k tbn, 60 tbc (default)
    Metadata:
      VARIANT_BITRATE : 0
      DURATION        : 00:08:00.233000000
    Stream #0:1: Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      VARIANT_BITRATE : 0
      DURATION        : 00:08:00.238000000
```

But VLC claims it's 30.00030. I will test what happens if I force ``-r 30`` during the encode.

Debugging the exact place the error happens will likely require someone who understands AV1 muxing and decoding. Perhaps the free one above is enough to see what is broken.

**Comment by gcp** [comment]
Changing to ``-r 30`` didn't do anything. It also seems that the FPS indication in VLC doesn't mean much as it is inferred from the duration.

But the exact same encoder settings, using SVT-AV1, produce a (fast) seekable .MP4 file. Whereas the .MKV breaks the encoders. So that also points at a muxing/decoding issue.

**Comment by jbkempf** [comment]
> thank you guys, so in summary:
> 
>     * this is reproducible with both libaom and svt-av1
> 
>     * decoder issue shows up on both libaom and libdav1d
>       we're either looking at ffmpeg muxing or VLC ?
> 

So what's the conclusion here?

**Comment by gcp** [comment]
>So what's the conclusion here?

There's either a bug in how ffmpeg muxes AV1 into MKV/WebM, or with how VLC decodes/demuxes it (when using fast seeking). We don't know which.

**Comment by 1480c1** [comment]
I am able to reproduce with vlc 3.0.12

**Comment by jbkempf** [comment]
Or both? :D 

Does it happen with --demux=ffmpeg in VLC?

**Comment by 1480c1** [comment]
Running `& 'C:\Program Files\VideoLAN\VLC\vlc.exe' --demux=ffmpeg .\SVTAV1-G300-F24.webm` and I cannot get the issue to reproduce

**Comment by jbkempf** [comment]
and --demux=matroska you can reproduce?

**Comment by 1480c1** [comment]
running `& 'C:\Program Files\VideoLAN\VLC\vlc.exe' --demux=matroska .\SVTAV1-G300-F24.webm` I get
```none
Your input can't be opened:
VLC is unable to open the MRL 'file:///C:/Users/cddeg/Nextcloud/Downloads/SVTAV1-G300-F24.webm'. Check the log for details.
```
running `& 'C:\Program Files\VideoLAN\VLC\vlc.exe' --demux=mkv .\SVTAV1-G300-F24.webm` and I can reproduce it

**Comment by jbkempf** [comment]
OK, So either FFmpeg muxing or VLC matroska demuxer issue.

Bringing @robux4

**Comment by robUx4** [comment]
I was able to reproduce the issue.  I opened an issue in VLC with a link to `SVTAV1-G300-F24.webm` and steps to reproduce.
I did not have the issue with the AVC file.
https://trac.videolan.org/vlc/ticket/25406
