### ISSUE TITLE
Clarify run-time encoder configuration output regarding CQP/CRF

### ISSUE THREAD

**Issue by veikk0** [AOMediaCodec/SVT-AV1#1675]
If I understood #1539 correctly, CRF has replaced CQP as the default rate control mode for `--rc 0`. However, the encoder config output shown at runtime still shows CQP as the BRC mode:

>`SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange			: CQP / 45 / 0 / 0 `

Also, if CRF is now the default RC mode, there should probably be a --crf option. And it'd be nice if this was mapped to the -crf option in FFmpeg.

**Comment by Felixkruemel** [comment]
That's confusing.

ffmpeg -qp -rc 0 is essentially -crf. So that really needs to be changed
