### ISSUE TITLE
[Announcement] Repo moving to gitlab

### ISSUE THREAD

**Issue by hassount** [AOMediaCodec/SVT-AV1#1679]
After completing #1531 , the project is now ready to move to gitlab. 

- The plan is to move the repo by February 10th, 2021. 
- The new destination will be https://gitlab.com/AOMediaCodec/SVT-AV1
- The existing svt-av1 mirror repo in the link above will deleted
- This repo will move with all issues / PRs in the new location.

**Comment by EwoutH** [comment]
I guess it’s time for me to finally learn GitLab CI. @1480c1, is there anything you currently need help with?

**Comment by 1480c1** [comment]
Right now I'm trying to get a Windows runner setup using docker, me and @ePirat often talk about CI stuff in #svt on irc, right now finishing up https://gitlab.com/1480c1/SVT-AV1/-/pipelines/248874562, so we pretty much have everything done

**Comment by jonsneyers** [comment]
Can I ask why this repo move is done?

**Comment by hassount** [comment]
> Can I ask why this repo move is done?

It's to combine projects and resources in one location.
