### ISSUE TITLE
External video denoising for Film Grain Synthesis  

### ISSUE THREAD

**Issue by waveletbeam** [AOMediaCodec/SVT-AV1#1683]
Video denoising can be very processing intensive and the different solutions are delivering different quality levels. It would be very helpful, if the SVT-AV1 internal video denoising step can be exchanged with an external one. My suggestion is to support four use cases.

**Use Case 1 application level:** The video denoising will be done outside the application and on command line the original and the denoised video will be provided.

**Use Case 2 application level:** The video denoising and the Film Grain Table generation will be done outside the application and on the command line the original video, the denoised video and the film grain table will be provided.

**Use Case 3 API level:** The video denoising will be done inside the application via an external API call.

**Use Case 4 API level:** The video denoising and the Film Grain Table generation will be done inside the application but via an external API call.

The beauty of film grain is back in the digital world. The grain will be reduced before encoding and transmitted via a grain table in the AV1 bitstream. After decoding the grain is added back and now it is possible to enjoy film look even at ultra low bitrates. This AV1 encoded file was processed with the Wavelet Beam Grain & Noise Management solution using the Film Grain Synthesis technology. Please note that only Google Chrome is supporting all AV1 features at the moment.
https://waveletbeam.com/index.php/av1-film-grain-synthesis

**Comment by hassount** [comment]
@waveletbeam thank you for the detailed issue, this is definitely a great area for contributions.
