### ISSUE TITLE
Red pixels

### ISSUE THREAD

**Issue by Ballevill** [AOMediaCodec/SVT-AV1#1690]
Hi, I have this error:

After conversion, red pixels are shown in the video file 

Photo:
https://ibb.co/b58yf84

Link to the article
https://developers.google.com/media/vp9/settings/vod

Link to the source file
http://ftp.nluug.nl/pub/graphics/blender/demo/movies/ToS/tearsofsteel_4k.mov

I have cut the version to 800mb. 

https://drive.google.com/file/d/1XRiBVh32Jz_NlbeLlXAd4qM9WWNj0sVz/view?usp=sharing

Most movies encode correctly, but that's what I have a problem with.

**Comment by hassount** [comment]
@Ballevill thank you for the bug report. This repo is only a mirror repo can you please log your issue at https://gitlab.com/AOMediaCodec/SVT-AV1/-/issues
