### ISSUE TITLE
Question: Hardware encoding with AV1

### ISSUE THREAD

**Issue by benpar2** [AOMediaCodec/SVT-AV1#1691]
Hello.
Recently Intel released the new GPU series, Intel Arc, that supports  hardware encoding of AV1. They claim its speed 50 times faster than software encoding. I’d like to know what’s its codec name, is it SVT-AV1? If yes, how can we use it?
I would appreciate your answer.

**Comment by 1480c1** [comment]
Hi @benpar2, this is the incorrect repo to report issues or ask questions at, the other [open issue](https://github.com/AOMediaCodec/SVT-AV1/issues/1688) and the front page mention that the canonical repo is at <https://gitlab.com/AOMediaCodec/SVT-AV1> now.

To answer your question, SVT-AV1 is a separate team and effort from the Intel Arc team and SVT-AV1 is fully software only and has no hardware encoding component other than using your CPU and it's capabilities. I am not particularly aware if it has a special name. I am not sure if you can use it without the hardware, but I can only assume you can use it through Intel's pre-existing apis such as quick sync
