### ISSUE TITLE
How to identify a inter frame is P or B frame

### ISSUE THREAD

**Issue by danduabhishek** [AOMediaCodec/SVT-AV1#1692]
As per my understanding, Av1 doesnt have the P or B frames. it has Inter frame as per the standard. How can i identify current frame is P or B frame from the Header information. which parameters in header section will help.

**Comment by 1480c1** [comment]
1. This is the wrong repo to be opening issues in as mentioned in the README on the front page
> The canonical URL for this project is at https://gitlab.com/AOMediaCodec/SVT-AV1

and the sidebar
> This repo is set as a mirror to the gitlab repo. Please join us at https://gitlab.com/AOMediaCodec/SVT-AV1. 

and in the only other issue open
> Please do not create any issues here. Please go to: https://gitlab.com/AOMediaCodec/SVT-AV1

2. You would be better off asking dav1d or aom as they can be considered canonical sources for decoding. You could try using ffprobe to get the frame type as one of the types specified in https://github.com/FFmpeg/FFmpeg/blob/6076dbcb55d0c9b6693d1acad12a63f7268301aa/libavutil/avutil.h#L272-L281

If you are confident in your backtracking ability, you try using the info provided in https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libdav1d.c#L421 to go through dav1d's source code to see how they decode the frame type from the header. Possible hint is https://code.videolan.org/videolan/dav1d/-/blob/master/src/obu.c#L394
