### ISSUE TITLE
cbr implmentation request

### ISSUE THREAD

**Issue by foroot** [AOMediaCodec/SVT-AV1#1693]
hi all, recently I tested svt-av1 v1.1.0-35 encode through ffmpeg-master cmd, found that cbr method seems not fully implemented, the full ffmpeg test cmd like this: "ffmpeg.exe -pix_fmt yuv420p -r 60 -s 1280x720 -i 720p.yuv -c:v libsvtav1 -svtav1-params "preset=5:rc=2:tbr=10m:max-qp=32:min-qp=3" -r 60 -g 30 -pix_fmt yuv420p -f mp4 -y 720p_cbr.mp4", 
1. shows cbr rate control not supported for PRED_RADOM_ACCESS then switch to vbr mode
![1280X1280](https://user-images.githubusercontent.com/33152153/181413770-52806b17-053a-466f-b8c7-45496506800b.PNG)
2. add "pred-struct=1" in svtav1-params like this: "ffmpeg.exe -pix_fmt yuv420p -r 60 -s 1280x720 -i 720p.yuv -c:v libsvtav1 -svtav1-params "preset=5:pred-struct=1:rc=2:tbr=10m:max-qp=32:min-qp=3" -r 60 -g 30 -pix_fmt yuv420p -f mp4 -y 720p_cbr.mp4", cbr mode enabled but shows not fully implemented
![1280X1280 (1)](https://user-images.githubusercontent.com/33152153/181415582-a2b6f6c5-9542-4bcd-8a79-aa6a4f8c4d02.PNG)
so I wonder whether I made a mistake or the cbr mode is not fully implemented indeed

**Comment by 1480c1** [comment]
https://github.com/AOMediaCodec/SVT-AV1/issues/1688


Wrong place to open an issue
