### ISSUE TITLE
[QUESTION] Why look_ahead_distance must be equal to intra_period_length if rc_mode VBR or CBVR?

### ISSUE THREAD

**Issue by murillo128** [AOMediaCodec/SVT-AV1#202]
According to 
https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Source/Lib/Encoder/Codec/EbEncHandle.c#L2641

The look  look_ahead_distance must be equal to intra_period_length if rc_mode VBR or CBVR ,but is there any reason why  this is enforced?

Ideally I would like to configure the encoder with:

```
  config.intra_period_length = -1;
  config.look_ahead_distance = 0;
```

**Comment by hassount** [comment]
@murillo128 
Thank you for your comment, the configuration you are proposing is not currently supported by the RC algorithm. Once it gets added, we will then be able to remove this restriction

**Comment by agouaillard-cosmo** [comment]
Hi hassount, any update on this? What is the status of the real-time mode?

**Comment by hassount** [comment]
> Hi hassount, any update on this? What is the status of the real-time mode?

@agouaillard-cosmo sorry for the late reply on this, the comment date and the lack of a tag, makes it quite weird. 
the direction is still that VOD applications will be the focus this year.
