### ISSUE TITLE
Add Constrained Quality (CQ) rate-control mode

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/SVT-AV1#343]
A true Constrained Quality (CQ) rate-control mode would be a very useful feature. Currently the constrained variable bitrate allows some sort of constrained mode, but not with a maximum bitrate of constant quality. It's very useful for situations where you have limited decoding or bandwidth capabilities.

The Constrained Quality mode should function identical to the Constant Quality mode, but with an upper bitrate limit. So `-q 25 -max-br 500000` for example. See also the [FFmpeg libaom AV1 Encoding Guide](https://trac.ffmpeg.org/wiki/Encode/AV1) as example.

Also, I don't think an upper quality `-max-qp` it that useful. A upper bitrate (`-max-br`) would be better (but both can be kept).

**Comment by gnafuthegreat** [comment]
I think this is a good idea.  Presumably hardware decoders will only support up to a certain level, and this will probably tie into those restrictions.  It would be nice to have constant quality but still target a certain level in the long run, and at least target a max bitrate in the short term.
