### ISSUE TITLE
Re-add converted SSE assembly

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/SVT-AV1#365]
Related to #262.

With #59 and #112 some SSE2 and SSE4.1 assembly got removed and replaced by AVX2 assembly. While I agree it shouldn't be a priority to add new assembly for old SIMD extentions, removing it is just harming performance unnecessary. It should be added back.

@spawlows Are you willing to assign this to yourself?

**Comment by gnafuthegreat** [comment]
At home, I don't have any processors with AVX2.  However, I do have an older i5 that is otherwise pretty fast and would benefit from SSSE3/SSE4.1 SIMD :-).  Intel is still producing processors without AVX2, such as my fairly recent Celeron J3160.
