### ISSUE TITLE
Document speed features

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/SVT-AV1#52]
Would be useful if the speed features got documented in the [user guide](https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.md), so that you know exactly what features are enabled in encoder modes 0 to 3.

**Comment by hassount** [comment]
@EwoutH 
At this early stage, we are still implementing the feature leavels for the presets, once we reach a stable version, we would be able to generate this. Maintaining it, would otherwise be a nightmare
