### ISSUE TITLE
Banding artifacts

### ISSUE THREAD

**Issue by Ilya87** [AOMediaCodec/SVT-AV1#616]
I encoded this (https://yadi.sk/i/qBkjd3TzJ_yBQQ) video with the latest git version (on Arch Linux x86_64).
`SvtAv1EncApp -i stdin -w 1920 -h 1080 -fps-num 24000 -fps-denom 1001 -enc-mode 4 -rc 0 -q 15 -intra-period 23 -lad 23 -n 749 -b eva_svt-av1_q15.bin` - for 8 bit encoding
And
`SvtAv1EncApp -i stdin -w 1920 -h 1080 -fps-num 24000 -fps-denom 1001 -enc-mode 4 -rc 0 -q 15/14 -intra-period 23 -lad 23 -bit-depth 10 -n 749 -b eva_svt-av1_q15.bin` - for 10 bit -q 15/14 (-pix_fmt yuv420p10le option for ffmpeg was used).

Results: with -q 14 (5672 kb/s) and -q 15 (5262 kb/s) 10 bit there is visible flickering (temporal) banding. With -q 15 (4586 kb/s) there are quite good visible banding artifacts. In comparison with x264 -crf 15 10 bit (3818 kb/s) (videofile is the same folder) banding artifacts are not present.
https://yadi.sk/d/CawCiQXY_brqOw

svt_q14_10bit
![banding_svt_q14_10bit](https://user-images.githubusercontent.com/1446573/65043764-3cb59180-d964-11e9-8297-0225ec947a80.png)
svt_q15_10bit
![banding_svt_q15_10bit](https://user-images.githubusercontent.com/1446573/65043782-4808bd00-d964-11e9-96f4-5aa0d5852a5a.png)
svt_q15
![banding_svt_q15](https://user-images.githubusercontent.com/1446573/65043795-522abb80-d964-11e9-86fa-bcdb5f0c2540.png)
x264_crf15_10bit
![banding_x264_crf15_10bit](https://user-images.githubusercontent.com/1446573/65043827-666eb880-d964-11e9-8ad1-8690fd833a45.png)

**Comment by AlexBoswellVCD** [comment]
When I run `SvtAv1EncApp -i Evangelion1.11_test_.mkv -w 1920 -h 1080 -fps-num 24000 -                                                                                                                 fps-denom 1001 -enc-mode 8 -rc 0 -q 15 -intra-period 23 -lad 23 -bit-depth 10 -n 749 -b eva_svt-av1_q15_m8.bin`

I get the following error

```
-------------------------------------------
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.6.0
SVT [build]  :  GCC 5.4.0 20160609       64 bit
LIB Build date: Jul 18 2019 15:59:17
-------------------------------------------
Number of logical cores available: 44
Number of PPCS 78
-------------------------------------------
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 10 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
SVT [config]: FrameRate / Gop Size                                              : 30 / 24
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 15 / 23 / 0
-------------------------------------------
Encoding       749
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
         749            30.00 fps               1645129963              527144.45 kbps


Channel 1
Average Speed:          7.879 fps
Total Encoding Time:    95058 ms
Total Execution Time:   97373 ms
Average Latency:        10591 ms
Max Latency:            13453 ms
Segmentation fault (core dumped)

```

**Comment by Ilya87** [comment]
> When I run `SvtAv1EncApp -i Evangelion1.11_test_.mkv -w 1920 -h 1080 -fps-num 24000 - fps-denom 1001 -enc-mode 8 -rc 0 -q 15 -intra-period 23 -lad 23 -bit-depth 10 -n 749 -b eva_svt-av1_q15_m8.bin`
> 
> I get the following error
> 
> ```
> -------------------------------------------
> SVT-AV1 Encoder
> SVT [version]:  SVT-AV1 Encoder Lib v0.6.0
> SVT [build]  :  GCC 5.4.0 20160609       64 bit
> LIB Build date: Jul 18 2019 15:59:17
> -------------------------------------------
> Number of logical cores available: 44
> Number of PPCS 78
> -------------------------------------------
> SVT [config]: Main Profile      Tier (auto)     Level (auto)
> SVT [config]: EncoderMode                                                       : 8
> SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 10 / 1 / 0
> SVT [config]: SourceWidth / SourceHeight                                        : 1920 / 1080
> SVT [config]: FrameRate / Gop Size                                              : 30 / 24
> SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
> SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 15 / 23 / 0
> -------------------------------------------
> Encoding       749
> SUMMARY --------------------------------- Channel 1  --------------------------------
> Total Frames            Frame Rate              Byte Count              Bitrate
>          749            30.00 fps               1645129963              527144.45 kbps
> 
> 
> Channel 1
> Average Speed:          7.879 fps
> Total Encoding Time:    95058 ms
> Total Execution Time:   97373 ms
> Average Latency:        10591 ms
> Max Latency:            13453 ms
> Segmentation fault (core dumped)
> ```

You MUST convert it to yuv format first. https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Docs/svt-av1_encoder_user_guide.md#input-video-format

**Comment by clavinet** [comment]
I just tested the latest git master and there's still banding in dark gradients, unless you throw ridiculous bitrate at it (cqp <=4)
