### ISSUE TITLE
Expose features/tools at the encoder configuration

### ISSUE THREAD

**Issue by joelsole** [AOMediaCodec/SVT-AV1#687]
Encoder features/tools to be controlled via configuration flags: enable turning on/off AV1 coding tools for finer control of complexity/efficiency tradeoffs and for easier testing & development.

List of tools to include:

- [X] RDOQ `-rdoq`
- [x] allow_intrabc
- [X] allow_warped_motion `-local-warp`
- [x] atb_mode `-atb`
- [ ] cdf_mode `-cdf`
- [X] combine_class12 `-class-12`
- [X] edge_based_skip_angle_intra `-intra-edge-skp`
- [X] enable_interintra_compound `-interintra-comp`
- [X] enable_restoration `-restoration-filtering`
- [x] enable_cdef `-cdef`
- [X] fractional_search64x64 `-frac-search-64`
- [X] frame_end_cdf_update_mode `-framend-cdf-upd-mode`
- [X] global-motion `-global-motion`
- [X] is_nsq_table_used `-nsq-table-use`
- [X] mfmv_enabled `-mfmv`
- [X] new_nearest_near_comb_injection `-new-nrst-near-comb`
- [X] nx4_4xn_parent_mv_injection `-nx4-4xn-mv-inject`
- [X] over_boundary_block_mode `-over-bndry-blk`
- [ ] perform_quantize_fp `-quantize-fp`
- [X] prune_ref_frame_for_rec_partitions `-prune-ref-rec-part`
- [X] prune_unipred_at_me `-prune-unipred-me`
- [X] redundant_blk `-redundant-blk`
- [X] spatial_sse_full_loop `-spatial-sse-fl`
- [X] trellis_quant_coeff_optimization `-trellis`
- [x] update_cdf `-updt-cdf`
- [X] use_subpel_flag `-subpel`
- [ ] adp_level
- [X] bipred3x3_injection `-bipred-3x3`
- [x] cdef_filter_mode
- [X] chroma_level `-chroma`
- [X] compound_mode (comp diff) `-compound`
- [ ] cu8x8_mode
- [ ] down_sampling_method_me_search
- [ ] fractional_search_method
- [ ] fractional_search_model
- [ ] full_loop_escape
- [ ] half_pel_mode
- [ ] HME tables
- [ ] hme_search_method
- [ ] ibc_mode
- [ ] interpolation_filter_search_blk_size
- [ ] interpolation_search_level
- [ ] intra_pred_mode
- [X] disable loop_filter_mode `-dlf`
- [ ] md_staging_mode
- [ ] ME Tables
- [ ] me_search_method
- [ ] mrp_mode
- [ ] nsq_search_level
- [ ] pic_depth_mode
- [X] pic_obmc_mode `-obmc`
- [X] predictive_me_level `-pred-me`
- [ ] quarter_pel_mode
- [ ] ref_count_used
- [ ] filter
- [ ] super_block_size
- [ ] tx_search_level
- [ ] tx_search_reduced_set
- [ ] tx_weight
- [ ] unipred3x3_injection
- [ ] wedge_mode
- [x] wn_filter_mode

**Comment by hassount** [comment]
@adaria is this issue still valid ? can we update it based on whatever options we know we have integrated ?

**Comment by adaria** [comment]
> @adaria is this issue still valid ? can we update it based on whatever options we know we have integrated ?

I ticked off the implemented options. The issue is valid but the list does need to be updated to prioritize which tools we want to expose on command line next. I'd need help with that. Thank you!
