### ISSUE TITLE
very prominent "blocking" artifacts(pixellation) during motion (2-pass VBR mode)

### ISSUE THREAD

**Issue by grill05** [AOMediaCodec/SVT-AV1#730]
I've encoded a 2-minute clip using both libaom (2-pass with crf=45, cpu-used=4) and svt (2-pass, rc=3, enc-mode=5). Both encodes have essentially the same bitrate. The source video was 720p. I've downscaled to 360p while testing (mainly because of encoding speed reasons)

The libaom encode looks very good visually. The Svt encode looks as good (to the naked eye) during periods of low motion. But when there is significant motion, there is very strong "pixellation" .Basically sections of the displayed frames collapse into blocks. It is very distracting visually

This is not just because of low bitrate or enc-mode. I've checked at higher bitrates/lower enc-modes. The video looks slightly better then(lower enc-mode/higher vbr), but these blocking artifacts are still present . Also, if libaom can produce such a good output at that bitrate/crf, then svt should also be able to.

For an example look between 10 and 20 seconds of this 2-minute clip. See how clear libaom output looks, and compare and contrast with the svt output. 
Also check between 1:50 and 2:00. There is some blurring in the libaom output, but it is mostly quite good. OTOH, the svt output has pretty bad pixellation (look at the running crowd).

Clips (2.9  Mb, 2 min, 360p)

[Clip 1](https://transfer.sh/yP8jd/clip.libaom.av1.8bit.mkv) (libaom, crf=45,2-pass,cpu-used=4)
[Clip 2](https://transfer.sh/thknp/clip.svt.enc_mode.5.webm) (svtav1encapp, 2 pass, enc_mode=5, -rc 3 -tbr 200000)
[Clip 3](https://transfer.sh/16bCOi/clip.svt.enc.mode.4.webm)  (svtav1encapp, 2 pass, enc_mode=4, -rc 3 -tbr 200000)
[Clip 4](http://www.solidfiles.com/v/gnxLBXpgkDVjz)  (svtav1encapp, 2 pass, enc_mode=4, -rc 2 -tbr 200000) 
Full command lines are [here](https://controlc.com/aaa6a50c)

EDIT: the blocking artifacts disappear if constant quantizer (-q) is used instead of VBR (-rc 3 -tbr). But using constant quantizer tends to make the bitrate increase enormously, and that kindof defeats the purpose of 2-pass encoding IMHO
EDIT2: Using -rc 2 reduces artifacts at the same bitrate (compared with -rc 3). clip is posted above.

**Comment by Fuchs4** [comment]
SVT AV1 is much faster, but speed always comes at a cost. SVT AV1 enc-mode 5 can not compete with libaom if it comes to quality/file size ratio. Try a lower enc-mode and you will see better results, at the cost of a much slower encode.

**Comment by grill05** [comment]
That is reasonable. The reason for posting this comparison was, that on my testbed, libaom -cpu-used=4 runs roughly as fast (slow) as svt -enc-mode 4. OTOH svt enc-mode=5 runs about 70% faster.The artifacts are still present with enc-modes 4 and 3.
The point was that this is a more or less "fair" comparison, in the sense that I'm comparing two equally fast (slow) modes, and both libaom and svt are being run in 2-pass mode. I agree that there will always be a speed/quality(bitrate) trade-off. But these artifacts are so significant, that the output is almost unwatchable.

**Comment by grill05** [comment]
Those artifacts can still be seen (during high motion periods) at enc-modes 4 and 3. For low-motion scenes, the svt output looks pretty good. And using -q makes them go away. So there might be something more involved here than a speed/quality trade-off.
On my testbed, enc-mode 4 and cpu-used=4 are roughly equally fast. So to get a speedup (vs liaaom) I have to use at least enc-mode 5 .

**Comment by hassount** [comment]
@grill05 
Thank you for your feedback.
The 2-pass implementation that is currently in the master is a milestone that is meant to add support of a second pass block level qp modulation / qp scaling / temporal filtering settings. The rate control implementation did not change and this work is planned for future future releases.
Apart from that and keeping the 2-pass away, you are comparing a vbr mode with a crf mode. The vbr implementation of svt would try to restrict the bit rates on a gop level to match the target bit rate. Such implementation is expected to impact the quality. You seem to be using rc mode 3 which has an even stricter bit rate allocation per gop than rc mode 2 and is targeted for use in live application where the speed is slightly more important than the quality to be achieved. 

CRF implementations on the other side would try to maximize the quality keeping the overall bit rate within a certain range, so it is much less constrained than VBR. SVT-AV1 does not have currently an implementation for crf with a restricted bit rate and such is planned for the future releases.

Now to help you get the best out of this encode, we can:
- First check that you are using the rc mode within its best known configuration, for that could you please share the command line with us ?
- To get around that I would suggest using the -q -rc 0 mode and try a few q [0-63] values to get approximately the same average bitrate (i would start with the same crf value as libaom). Such would maximize your quality gain.

**Comment by grill05** [comment]
@hassount thanks for the follow-up. 
The command line I used for svt was
`ffmpeg  -i input.mkv  -s 640x360   -an  -f yuv4mpegpipe -sn - | SvtAv1EncApp -i stdin -w 640 -h 360 -fps 24.0  -n 2877 -rc 3 -tbr 200000  -output-stat-file out.stat  -irefresh-type 2  -enc-mode 7 -enc-mode-2p 5 -b out.svt.mkv
ffmpeg  -i input.mkv  -s 640x360   -an  -f yuv4mpegpipe -sn - | SvtAv1EncApp -i stdin -w 640 -h 360 -fps 24.0  -n 2877 -rc 3 -tbr 200000  -input-stat-file out.stat  -irefresh-type 2 -enc-mode 5 -b out.svt.mkv`
Actually, 2-pass mode in libaom with a bitrate target looks pretty m\similar

**Comment by DesertCookie** [comment]
Saw on #623 this functionality might be in 0.8. Haven't found any documentation stating it actually made it into the spec to this day. Any progress?
