### ISSUE TITLE
[Documentation]: Add Codeowners file?

### ISSUE THREAD

**Issue by 1480c1** [AOMediaCodec/SVT-AV1#735]
"GitHub CODEOWNERS file is a simple way to automate away some of the pain associated with the review system on github, by automatically assigning reviewers to a pull request based on which files were modified."

Having a codeowners file can help delegate pr reviewers based on file or folder automatically and can help mark who is more familiar with certain files.

Something like
```none
* @hassount 
*.yml @kylophone # CI/CD
/ffmpeg_plugin @jsunintel # FFmpeg patches and docs
...
```

It seems it needs to be activated? (Unsure, I only recently noticed it)

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners

https://tech.people-doc.com/using-github-codeowners-file.html#targetText=GitHub%20CODEOWNERS%20file%20is%20a,on%20which%20files%20were%20modified

**Comment by hassount** [comment]
cool, let's look into adding this
