### ISSUE TITLE
Automate speed & coding efficiency testing with AWCY

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/SVT-AV1#87]
Part of #4.

On https://beta.arewecompressedyet.com there is a [single](https://beta.arewecompressedyet.com/?job=svt-av1-1) run of SVT-AV1. With a few big PR's coming in (tiling #81, superblocks #82, new speed profile #80), it would be extremely useful to have encoder speed and encoding efficiency continuously tested and monitored. AWCY looks at the moment like the best tool for that.

Maybe @tdaede can help a hand.

**Comment by kylophone** [comment]
Just updated the AWCY command line here: https://github.com/tdaede/rd_tool/pull/43

**Comment by tdaede** [comment]
The other thing needed for automated runs is a threads setting. AWCY allocates assuming that each process uses 1 thread.

**Comment by EwoutH** [comment]
Do we only want to test `-enc-mode 0`, or also other options? Is testing all speed settings frequently possible?

**Comment by tdaede** [comment]
As long as the svt-av1 cli parser lets later settings override earlier settings, you can use AWCY EXTRA_OPTIONS to do that.

**Comment by kylophone** [comment]
@hassount: afaik, single thread operation is not possible right now. Is that right?

**Comment by tdaede** [comment]
In particular, AWCY already runs an encoder instance for every image and quantizer, on machines with many cores. Using as many threads as detected on the machine is not only inefficient but will also exhaust RAM.

**Comment by kylophone** [comment]
> In particular, AWCY already runs an encoder instance for every image and quantizer, on machines with many cores. Using as many threads as detected on the machine is not only inefficient but will also exhaust RAM.

I agree.

**Comment by EwoutH** [comment]
So what's the lowest realistic option for the number of threads? Would 4 or 8 work?

**Comment by kylophone** [comment]
> So what's the lowest realistic option for the number of threads? Would 4 or 8 work?

Good question. The first problem to deal with is the fact that this is not a tunable param. By default, the encoder takes over everything on the system, which like @tdaede said is generally a bad approach.

**Comment by hassount** [comment]
@kylophone @EwoutH @tdaede 
As the encoder is designed to be ran in data centers on multi core servers, it's mapped to take on as many cpu cycles as possible so that is uses it all. it might sound inefficient right now as the CPU utilization is not capping to ~100%, but soon enough it will.That said, we can add an option to restrict the execution on 1 logical core only, it will still use a few threads, but it won't take on all the cpus, would that work ? this option is implemented in SVT-HEVC -lp that would restrict the threads to live on a particular set of cpus.

**Comment by tdaede** [comment]
Yes, that's okay. Basically I want to override its automatic CPU detection and have it act as if it detected less CPUs. I think -Ip is exactly what I want.

**Comment by hassount** [comment]
ok sounds good, we'll do, #92

**Comment by EwoutH** [comment]
#113 is now merged, `-lp` can be used to limit the number of logical processors.

**Comment by EwoutH** [comment]
@tdaede @kylophone Can SVT-AV1 be integrated in AWCY, or is anything else needed?

**Comment by EwoutH** [comment]
@tdaede @kylophone @hassount What's the current status of SVT-AV1 integration in AWCY? I see a few run [popping up now](https://beta.arewecompressedyet.com/?job=svt-av1%402019-03-15T01%3A14%3A29.113Z&job=svt-av1-1&job=%402019-03-19T20%3A06%3A30.414Z), is it already automatically triggered on certain events? (MRs, commits, etc.)

**Comment by tdaede** [comment]
It works and you can submit runs. We're working on adding the Github hook now.
