### ISSUE TITLE
Add option to skip first n frames of video

### ISSUE THREAD

**Issue by EwoutH** [AOMediaCodec/SVT-AV1#91]
A `-skip` option that skips the first n frames of the input clip would be very useful. So if `-skip 360` is used encoding should start at frame 361. And `-skip 360 -n 120` should encode frames 361 to 480.

**Comment by hassount** [comment]
This is open to contributions as it is hopefully straight forward :)

**Comment by JackZhouVCD** [comment]
@EwoutH so right now our encoder wraps around the input stream when the encoding is longer than the stream. How do you think adding a skip feature should play with that? Simply start at the frame to skip to then wrap over to start at the beginning of the video?

**Comment by EwoutH** [comment]
@JackZhouVCD I think that would be ok, just skip n frames once and then continue to loop the whole video.
