### ISSUE TITLE
Copy encoding progress style from x264/x265

### ISSUE THREAD

**Issue by AtakSnajpera** [AOMediaCodec/SVT-AV1#945]
This issue is sort of appendix to this one https://github.com/OpenVisualCloud/SVT-AV1/issues/779
started by stax76 

Hi! I'm the author of RipBot264 and I would like to suggest changes to how encoder informs user about his work.

Here is an example style used in x265.
y4m  [info]: 640x272 fps 24000/1001 i420p8 sar 1:1 unknown frame count
raw  [info]: output file: \\XEON-PC\RipBot264temp\job1\Chunks\1.265
x265 [info]: HEVC encoder version 3.2+22-a8a2c4c37267
x265 [info]: build info [Windows][GCC 9.2.0][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
x265 [info]: Main 10 profile, Level-2.1 (Main tier)
x265 [info]: Thread pool created using 16 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 4 / wpp(17 rows)
x265 [warning]: Source height < 720p; disabling lookahead-slices
x265 [info]: Coding QT: max CU size, min CU size : 16 / 8
x265 [info]: Residual QT: max TU size, max depth : 16 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 9 / 2 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 24 / 240 / 40 / 5.00 
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / off / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 2 / 1.0 / 16 / 1
x265 [info]: Rate Control / qCompress            : CRF-20.0 / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 early-skip rskip signhide tmvp b-intra
x265 [info]: tools: strong-intra-smoothing deblock sao
                                                                                
x265 [info]: frame I:     23, Avg QP:17.34  kb/s: 655.18  
x265 [info]: frame P:    401, Avg QP:21.92  kb/s: 730.71  
x265 [info]: frame B:   1014, Avg QP:26.79  kb/s: 122.20  
x265 [info]: Weighted P-Frames: Y:11.2% UV:4.2%
x265 [info]: consecutive B-frames: 13.4% 12.3% 12.7% 44.8% 16.7% 

encoded 1438 frames, 202.19 fps, 300.41 kbps

when frames are still being encoded progress looks like this 
[85.1%] 9323/10961, 24.96 fps, 993.49 kbps, eta 0:01:08

It would be great if instead of inventing the wheel again you could just use what we have been already using for years (x264/x265). Trust me GUI makers (and others) will love this cosmetic change!

**Comment by hassount** [comment]
@kylophone

**Comment by stax76** [comment]
Do you receive progress in RipBot264? It's the only CLI app where StaxRip don't receive progress and I'm not really willing to debug this because as I said it before I don't believe in this encoder.

**Comment by stax76** [comment]
The problem in staxrip is that svtav1 progress update is done without writing line breaks, staxrip depends on the [Process.OutputDataReceived](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.outputdatareceived?view=netframework-4.8) event which is only fired when a line break is written.

I would like to request that for every progress update a line break is written.

**Comment by stax76** [comment]
Problem is at least for staxrip solved now.
