### ISSUE TITLE
Limit block size

### ISSUE THREAD

**Issue by weter11** [AOMediaCodec/SVT-AV1#950]
Hi. Is it possible to manually limit block sizes from all variants of 128x128 to 16x16? I can't understand why codec don't produce at least the same quality as x264 at medium bpp (0.05), maybe it can't correct decide where on the picture to use less bitrate and smaller blocks, because sometimes it even blurry parts of background mostly static image for no reason, sometimes it blurry parts of clothes that maybe looks a bit better in terms of original texture structure, but even with compression noise x264 looks sharper and with better understandable image details.
Input videos 3840x2160 30fps encoded to x264 veryslow and av1 speed 4.

**Comment by hassount** [comment]
@adaria this can be added as part of the config flags work, would you like to take a shot at it ?

**Comment by weter11** [comment]
Sure, what to do?

**Comment by adaria** [comment]
Sure, looking into it.
