### ISSUE TITLE
Why hierarchical_levels 0/1/2 are not allowed to be used in verify_settings() with the internal code being ready?

### ISSUE THREAD

**Issue by elintencent** [AOMediaCodec/SVT-AV1#973]
Why hierarchical_levels 0/1/2 are not allowed to be used in verify_settings() with the internal code being ready?
    if (config->hierarchical_levels != 3 && config->hierarchical_levels != 4) {
        SVT_LOG("Error instance %u: Hierarchical Levels supported [3-4]\n", channel_number + 1);
        return_error = EB_ErrorBadParameter;
    }

**Comment by hassount** [comment]
This is a WIP

**Comment by elintencent** [comment]
What encoder's features are not ready for hierarchical_levels 0/1/2? When the parameter checking in verify_settings() is removed, it seems that hierarchical_levels 0/1/2 can run.

**Comment by hassount** [comment]
the encoder runs but there's a largely unexpected BDR loss, therefore it's considered broken for now.

**Comment by LiuAnmin** [comment]
> the encoder runs but there's a largely unexpected BDR loss, therefore it's considered broken for now.

May I have the information regarding the target release date?

Whether non-ref B will be included in this WIP?

**Comment by liuanmin2017** [comment]
> This is a WIP, although the pred structure support might be ready, the encoder's features are not, and such would need to be fixed before enabling them

May I have the information regarding the target release date?

Whether non-ref B will be included in this WIP?

**Comment by kedartatwawadi** [comment]
Has this been addressed now? I see that the WIP #1047 being closed now. 
On trying on a few videos, it does seem like SVT-AV1 is already significantly better than H265, H264 with `hierarchical_levels=0` flag.

**Comment by hassount** [comment]
@kedartatwawadi #1571 is doing this.
